### ISSUE TITLE
emitC flow not working after IREE candidate-20220803.224

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#10000]
### What happened?

Generate following error message running models (mnist, mobilenet, etc.)

```
10:10:33.4086 [ERROR] "iree/runtime/src/iree/vm/ref.c:204: INVALID_ARGUMENT; source ref type mismatch; while invoking native function module.__init; "
10:10:33.4087 [ERROR] "[ 0]   native module.__init:lu -"
```

### Steps to reproduce your issue

Use https://github.com/hcindyl/iree-rv32-springbok/tree/iree-build-224 and follow the README.md to build and run the programs

Result:
```
Failed Tests (3):
  Model tests :: float_model/mnist_emitc_static_test.txt
  Model tests :: float_model/mobilenet_v1_emitc_static_test.txt
  Model tests :: quant_model/mobilenet_v1_emitc_static_test.txt
```

### What component(s) does this issue relate to?

vm, emitc

### Version information

between candidate-20220801.222 to candidate-20220803.224

**Comment by marbre** [comment]
Thanks for reporting @hcindyl!

It seems we have the same problem with the vision inference / MNIST [sample](https://github.com/iml130/iree-bare-metal-arm/tree/main/samples/vision_inference) compiled with iree-bare-metal-arm and running it on Renode:
```
15:20:30.1190 [INFO] usart2: [host: 14.71s (+14.71s)|virt: 0.5ms (+0.5ms)] INVALID_ARGUMENT
```
FYI, the vision inference is not a full e2e sample since it relies on [samples/models/mnist.mlir](https://github.com/iree-org/iree/blob/main/samples/models/mnist.mlir). With other words we start with MHLO input and not with a TF/TFLite model.

I can further confirm that candidate-20220731.221 works as it should. I will look into what is going wrong.

**Comment by marbre** [comment]
The failure we're seeing is related to commit 76bf2f3 (the merge of #9754). The last commit working for me is d46c881.

**Comment by alliemartens** [comment]
@benvanik Could you help to triage this issue?

**Comment by simon-camp** [comment]
Short update:

This is caused by aliasing of ref variables in the EmitC conversion. My current work is [here](https://github.com/simon-camp/iree/tree/issue-10000).
Now [this test function](https://github.com/iree-org/iree/blob/fe0e4dd033959a55ee5e3a353d127a7232e4713e/runtime/src/iree/vm/test/control_flow_ops.mlir#L167) gets miscompiled by the EmitC conversion as the results are returned in the wrong order.

I'll continue working on this next week.

**Comment by simon-camp** [comment]
@hcindyl  This should be fixed with #10094.

I only tested this on the [static library sample](https://github.com/iree-org/iree/tree/main/samples/static_library) altered for the [MNIST model](https://github.com/iree-org/iree/blob/main/samples/models/mnist.mlir) though.

**Comment by hcindyl** [comment]
I tested with the examples in https://github.com/hcindyl/iree-rv32-springbok/ and all tflite/mlir models passed.

**Comment by hcindyl** [comment]
Will close the issue once the commit lands in the candidate release.

**Comment by hcindyl** [comment]
The commit landed in https://github.com/iree-org/iree/releases/tag/candidate-20220816.237
