### ISSUE TITLE
linalg.conv_2d_nhwc_hwcf fails on vectorization for quantized types

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#10790]
The following program fails to compile on Mac OS due to a segmentation fault. See the attached stack trace

`iree-compile --iree-hal-target-backends=llvm-cpu <program>`

```
module {
  func.func @main(%arg0: tensor<1x14x16x32xi8>, %arg1: tensor<3x4x32x16xi8>) -> tensor<1x12x13x16xi32> {
    %c0_i32 = arith.constant 0 : i32
    %0 = tensor.empty() : tensor<1x12x13x16xi32>
    %1 = linalg.fill ins(%c0_i32 : i32) outs(%0 : tensor<1x12x13x16xi32>) -> tensor<1x12x13x16xi32>
    %2 = linalg.conv_2d_nhwc_hwcf {dilations = dense<1> : tensor<2xi64>, strides = dense<1> : tensor<2xi64>} ins(%arg0, %arg1 : tensor<1x14x16x32xi8>, tensor<3x4x32x16xi8>) outs(%1 : tensor<1x12x13x16xi32>) -> tensor<1x12x13x16xi32>
    return %2 : tensor<1x12x13x16xi32>
  }
}
```

[stacktrace.txt](https://github.com/iree-org/iree/files/9782620/stacktrace.txt)

**Comment by rsuderman** [comment]
This is the IR immediately before LinalgStrategyVectorizePass. Test using the line below

`iree-opt /tmp/test.mlir -iree-linalg-strategy-vectorize-pass`

[mlir.txt](https://github.com/iree-org/iree/files/9782659/mlir.txt)

**Comment by aaron-schneider** [comment]
Hi @MaheshRavishankar - can you assign a priority and remove the awaiting-triage label?

**Comment by MaheshRavishankar** [comment]
I dont have a mac, so I can repro. I am moving this to P2.....

**Comment by rsuderman** [comment]
@MaheshRavishankar  It appears to be blocking enabling the compilation for non-macs as well:
https://github.com/iree-org/iree/pull/10852

**Comment by MaheshRavishankar** [comment]
So there is a repro if I take your PR and build it locally?

**Comment by hanhanW** [comment]
Looks like an compilation error when vectorizing some conv ops. I can take over the issue.

  CC @vmurali since he's assigned to a related issue: https://github.com/iree-org/iree/issues/8905

**Comment by rsuderman** [comment]
I am having trouble reproducing on my linux machine. Not 100% sure what the build difference is that is causing the issue.

**Comment by benvanik** [comment]
could try with asan? (`-DIREE_ENABLE_ASAN` to cmake configure)

**Comment by rsuderman** [comment]
It appears to be an assertion which may explain why it didn't repo on my other builds. Rebuilding as debug with assertions.

**Comment by MaheshRavishankar** [comment]
actually if this is a convolution, it might just be that the dispatch is not going down the convolution pipeline. Convolution vectorization happens slightly differently. Using this would be more informative `--mlir-print-ir-before=iree-codegen-tile-and-distribute-to-workgroups --mlir-disable-threading` . If the dispatch isnt going down the convolution pipeline, that'd be the issue.

**Comment by hanhanW** [comment]
It is down to codegen because it failed in `vectorizeAsLinalgGeneric`, which is trying to vectorize the convolution op in a generic way. This is wrong because convolution has its own logic for vectorization.

I suspect that it failed in some assertions or conditions because the vectorizer assumes the element types match, but it's not in this case.

**Comment by dcaballe** [comment]
That makes sense. This error must be similar to the one for pooling when we try to vectorize it without a pattern (https://github.com/iree-org/iree/issues/10670)

**Comment by julianwa** [comment]
Setting to P0 for triage -- it's blocking some upstream work; please review and set a lower priority if appropriate

**Comment by hanhanW** [comment]
narrow it down to vectorization pass: https://gist.githubusercontent.com/hanhanW/5fcc9f9f881a2c16e873e16bd6e23385/raw

To repro: `iree-opt -linalg-single-tiling-expert-driver="vectorize" ~/repro.mlir`

This is because the generator does not recognize `arith.extsi`. Thus, it assumes it to be invalid case. Falling back to generic vectorizer is wrong in this case. It works if we update the check to `if (!isa<arith::ExtFOp, arith::ExtSIOp>(def))`.

https://github.com/llvm/llvm-project/blob/f357a412654cf5ae750a14b6f56900aaa029cec2/mlir/lib/Dialect/Linalg/Transforms/Vectorization.cpp#L1468

I can send out a patch to fix it... just need to write some lit tests.

**Comment by hanhanW** [comment]
https://reviews.llvm.org/D137208 should fix the issue.

**Comment by hanhanW** [comment]
landed the fix upstream
