### ISSUE TITLE
Long compilation time with `--iree-flow-enable-data-tiling`

### ISSUE THREAD

**Issue by pzread** [iree-org/iree#11434]
#11411 results in a long compilation time on benchmark suites.

Before it took 21m to build: https://buildkite.com/iree/iree-benchmark-android/builds/5070
After it took 1h38m to build: https://buildkite.com/iree/iree-benchmark-android/builds/5071

Since we also build the benchmark suite as tests on Github CI, this significantly slows down the CI: https://github.com/iree-org/iree/actions/runs/3624345554/jobs/6111542368

I also realized we forgot to enable the compilation time tracking on Android benchmarks, so we didn't catch this in the PR.

**Comment by pzread** [comment]
I'm still collecting the compilation time. But at least it looks like `MobileBertSquad_int8` takes more than 15mins to compile

**Comment by bjacob** [comment]
Tentatively reassiging to @hanhanW based on https://github.com/iree-org/iree/pull/11435#issuecomment-1338696302

**Comment by bjacob** [comment]
Summarizing here the result of the investigation so far in #11435 comments.

Reproduction (https://github.com/iree-org/iree/pull/11435#issuecomment-1338648648):

1. Get the benchmark-suite build (`cmake --build . --target iree-benchmark-suites`) to download and import models, so that this file is present in your build dir: `benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir `.
2. Reproduce the slow compilation time ( > 10 min here) with the new `--iree-flow-enable-data-tiling`:
```
$ time tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-flow-enable-data-tiling --iree-input-type=tosa --iree-llvm-target-cpu-features=+dotprod --iree-llvm-target-triple=aarch64-none-linux-android29 benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir -o /tmp/a.vmfb
```
3. Compare to the quick compilation time (~ 1 min here) with the old `--iree-flow-mmt4d-target-options`:
```
$ time tools/iree-compile --iree-hal-target-backends=llvm-cpu --iree-flow-mmt4d-target-options='arch=aarch64 features=+dotprod' --iree-input-type=tosa --iree-llvm-target-cpu-features=+dotprod --iree-llvm-target-triple=aarch64-none-linux-android29 benchmark_suites/TFLite/mobilebert-baseline-tf2-quant.tflite.mlir -o /tmp/a.vmfb
```

The diff in [this comment](https://github.com/iree-org/iree/pull/11435#issuecomment-1338696302) , disabling pack/unpack/setencoding/unsetencoding fusions with producers/consumers, fixes the compilation time regression.

**Comment by hanhanW** [comment]
Could be bad configuration about i8, which introduces tooooo many IRs. I'll take over the issue.
