### ISSUE TITLE
Fix fuse-operands.mlir test after integration

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#11765]
https://github.com/iree-org/iree/pull/11763 disables fuse-operands.mlir to make integration progress forward.

**Comment by hanhanW** [comment]
@ftynse thanks for the fixes in https://github.com/iree-org/iree/pull/11750. I cherry-pick the fixes to the integration. 
Only `[mlir] verify against nullptr payload in transform dialect` is not included. All the tests are passing except `fuse-operands`. Can one of you help fix the issue?

**Comment by ftynse** [comment]
This failure does not look related to `[mlir] verify against nullptr payload in transform dialect`, the internal pattern implementing the fusion fails to apply. Verification doesn't change patterns.

**Comment by ftynse** [comment]
This is actually due to https://github.com/llvm/llvm-project/commit/bcfd32adc4b658dc45aa8c338d5dd03837e2a0e4 that introduces a canonicalization breaking the precondition for https://github.com/iree-org/iree/blob/a81c3cf3f2f030a60254e66ba6ed711155ef9bf2/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/Fusion.cpp#L32-L33. IMO, this is yet another example for not running blanket canonicalization all over the place.

**Comment by ftynse** [comment]
#11772 will add a proper error message here.  I don't know what's the intended behavior given that pattern and, therefore, how to reenable the test beyond matching this error.

**Comment by matthias-springer** [comment]
I have a fix in #11714. Will re-activate the test in with that change.

**Comment by hanhanW** [comment]
Thanks for looking into it! I'll include the change in the integrate!
