### ISSUE TITLE
Caching allocator causes wrong computation result

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#12161]
### What happened?

Enabling the caching allocator causes numerical errors. In this [branch](https://github.com/nod-ai/SHARK-Runtime/tree/stateful-model-test) I have modified the python binding per the suggestion of @benvanik to enable quickly the caching allocator while waiting for the Python API to catch up.
There is a [test](https://github.com/nod-ai/SHARK-Runtime/tree/stateful-model-test/tests/e2e/models/stateful_model_test) there that reproduces the problem. I am not convinced that this test will reproduce reliably on other platforms.

### Steps to reproduce your issue

At the aforementioned branch run
```
python ./tests/e2e/models/stateful_model_test/stateful_model_test.py
```

### What component(s) does this issue relate to?

Compiler, Runtime

### Additional context

https://discord.com/channels/689900678990135345/706175572920762449/1073493760429789254

### Edit:
A more up-to-date version of the test can be found [here](https://github.com/nod-ai/SHARK-Runtime/tree/stateful-model-test-with-allocator-python-api).

**Comment by benvanik** [comment]
Can you provide an IR dump so we can reproduce? I might have a lead on this but need some IR to confirm.

**Comment by sogartar** [comment]
https://storage.googleapis.com/shark-public/boian/stateful_model_test_data.tar
There is MLIR bytecode inside.

**Comment by powderluv** [comment]
@benvanik any luck with this ?  @julianwa this could be a boost across all models we care about.

**Comment by benvanik** [comment]
I'll take a look today. I've got a utility in mind that will help isolate whether this is actually the caching allocator or something wrong with the model compilation (assuming zeroed memory).

**Comment by powderluv** [comment]
Thank you much appreciated

**Comment by benvanik** [comment]
What backends are you using?

Looking at the model compilation things seem fine and I can't spot how they'd cause trouble. I ran it through iree-benchmark-module with `--iree-flow-trace-dispatch-tensors` and every iteration has the same output.
Can you run with `--iree-flow-trace-dispatch-tensors`?

This is too complex to reproduce as it's stateful and I don't know your sequence of calls. This is what we made the yaml tracing stuff for but I'm not sure if there's anything on the python side that can generate them anymore - @stellaraccident is any of that still live they could use to dump a trace?

I've got a debug allocator which scribbles over memory and I'll send that out for review in a sec - you'll want to run with that afterward by adding `--device_allocator=debug` to test with just that, and then subsequently test `--device_allocator=caching --device_allocator=debug` (order matters, that layers the debug allocator on top of the caching allocator).

**Comment by benvanik** [comment]
#12337 has the debug allocator.

**Comment by sogartar** [comment]
The call sequence during testing is described [here](https://github.com/nod-ai/SHARK-Runtime/blob/572932a8104e26b24736897de8294c5023380558/tests/e2e/models/stateful_model_test/stateful_model_test.py#L102).
I was not able to make a small model that was failing with a single function call. @powderluv may point to a large model that failed in a single function call.
I will try with the debug allocator.

**Comment by benvanik** [comment]
Ah I see. Pretend I'm super overwhelmed and as much as I'd like to don't have the brain space to parse test framework code - make it as simple as possible and I'll be able to help you faster :)

Which backend are you using?

**Comment by sogartar** [comment]
@benvanik 
> Which backend are you using?

It is using `local-task`.

I picked up your changes for the Python allocators API 52de6a343be1870d6cffb627615090e70fabdc33 and adapted the test for it. The test is at [stateful-model-test-with-allocator-python-api](https://github.com/nod-ai/SHARK-Runtime/tree/stateful-model-test-with-allocator-python-api). I still get the error.
I was not able to make a stateless model that is also small that reproduces the problem. I don't know if it will help to have the test against the IREE C API. It will be a lot more code.

**Comment by stellaraccident** [comment]
If running from Python, setting the environment variable `IREE_SAVE_CALLS=/some/dir` will generate a sequence of calls that can be replayed with `iree-run-trace`. Not sure if it helps.

**Comment by sogartar** [comment]
@stellaraccident, is there a way to get a trace when running with `iree-run-trace`? The output gets truncated.

**Comment by benvanik** [comment]
do you mean the output tensors printed? I need to add a flag, but you can hack a larger number than 1024 in here:
https://github.com/google/iree/blob/c1def3f696c3f8246249d2933b0d5532430cbd81/runtime/src/iree/tooling/trace_replay.c/#L1010-L1012

**Comment by sogartar** [comment]
Ideally, you would have something similar to `iree-run-module`'s `--output=+file.npy`.

**Comment by benvanik** [comment]
Yeah, should be easy enough to support - the tool gets extremely little usage today so there hasn't really been any work done on it recently - if people start using it, though, I'll give it some love :)

**Comment by sogartar** [comment]
When I rerun with `iree-run-trace` the dump from `IREE_SAVE_CALLS` I don't observe any difference. The output is the same when running with the default allocator
```
iree-run-trace calls.yaml --device=local-task
```
 or running with
 ```
 iree-run-trace calls.yaml --device=local-task --device_allocator=caching --device_allocator=debug
 ```
 This is true even when removing the output truncation as @benvanik suggested.

**Comment by sogartar** [comment]
I wanted to submit another model that fails when running a single function just once. From 158 combinations of models and backends none of them has the issue.
Only Stable Diffusion is problematic as it needs to do 50 iterations. When I look at the results I see that wrong numbers are returned on the second call. This is true for 4 modules there. This is also the case for the reproducer I linked earlier in this issue.
This leads me to believe that the problem is related to having multiple calls.

**Comment by powderluv** [comment]
Thank you for narrowing it down further

**Comment by benvanik** [comment]
I'm not sure I see it narrowed down further - do you have explicit instructions and inputs for reproducing this without python involved? It sounds like above the calls.yaml **did not** reproduce it?

**Comment by sogartar** [comment]
> It sounds like above the calls.yaml **did not** reproduce it?

Yes, it did not. When I feed the same input to `iree-run-trace` I got the same output with or without changing the allocator.

> do you have explicit instructions and inputs for reproducing this without python involved?

I have not rewritten this to run against the IREE C API.

**Comment by benvanik** [comment]
Can you share your SAVE_CALLS output yaml and the mlirbc + compile commands? I can see if I can improve the iree-run-trace tooling so that it does reproduce, if it's possible to do so with it.

**Comment by sogartar** [comment]
Here it is [stateful_model_test_trace_dump.zip](https://github.com/openxla/iree/files/10902305/stateful_model_test_trace_dump.zip)

**Comment by sogartar** [comment]
Here it is [stateful_model_test_dump.zip](https://github.com/openxla/iree/files/10902436/stateful_model_test_dump.zip).
It is not exactly the same as the test. There it is ran for 10 iterations, but it actually fails on the second iteration, so I included only 2 in the trace to reduce its size.

**Comment by benvanik** [comment]
Thanks! I think #12525 will help build a reproducer for this as the current trace replay tool reparses each calls input instead of chaining them and that is likely hiding the issue. I'll also do #12526 which will make it easier to load/save the various I/O for verifying in python.

**Comment by benvanik** [comment]
Taking a look now with #12534 to see if I can reproduce. Of the dumps you posted which one is correct? (maybe include in the names next time - I know they're different because they have a diff but I'm not sure which I should trust is correct :)

**Comment by benvanik** [comment]
I'm not able to reproduce with the caching allocator and either trace, or traces I've set up making combinations of set_params/forward calls. Every call after a particular set_params will produce the same values. So either the traces aren't capturing the failing behavior or there may be something in the python layer that is causing issues. I'd __really__ like to rule out the python layer, though, so am looking hard for ways to reproduce it outside.

With #12534 I'm doing:
```
iree-run-trace --device=local-sync --print_call_outputs calls.yaml > a.txt
iree-run-trace --device=local-sync --print_call_outputs calls.yaml --device_allocator=caching > b.txt
diff a.txt b.txt
# no diff
```

The diff I see in your calls.yaml files is odd as it happens after the first forward call. I don't know how the caching allocator would impact that directly as I'd expect any failures to happen after the second call where the cached buffers are reused. I can't reproduce any differences and the first call to forward always outputs the same values:
```mlir
--- CALL[forward] ---
result[0]: hal.buffer_view
128x10xf32=[-2.83551 -2.17895 -2.04608 
--- CALL[forward] ---
result[0]: hal.buffer_view
128x10xf32=[-30.1292 -26.7821 -36.8049 -21.9871 -10.5653 
```

**Comment by benvanik** [comment]
I thought it weird that there are the parameter constants embedded in the program while also being set before use so I tried dropping them - you'll want to do that (no use compiling the big constants and bloating your vmfb if you're not using them) and if we enable referencing instead of copying immutable variables (constants) then that'll be required. It didn't help me in reproducing this but will help with memory consumption in larger models.

**Comment by sogartar** [comment]
I don't know if not setting the parameters makes any difference to the reproducability. This is a model I exported with IREE JAX. I don't know how to generate MLIR that has the function to set the parameters, but does not have them embedded also.
There is also the option to pass the parameters as well. For example if you want to have a pure training function you would pass the model weights and optimizer state along with the training batch. The function would also return them updated.

**Comment by stellaraccident** [comment]
I'm trying to follow the comment thread: is there a diff in the yaml trace? Didn't quite follow if there was and we couldn't explain it.

**Comment by sogartar** [comment]
When I run the Python test with and without caching allocator there is a difference in `calls.yaml`. When I run `iree-run-trace` with the dumped `calls.yaml` from the correct test (without caching allocator) I don't see a difference.

**Comment by benvanik** [comment]
You still need to tell me what's what :) Please reupload your files with more descriptive names ("good" "bad" "with_caching_allocator" "without_caching_allocator" etc) or link them with those descriptions - and also ensure they're identical (if the two have different number of calls and such that makes them impossible to analyze). I could be sitting here testing the wrong files.

The calls.yaml dumped from the python tooling today is unlikely to show any difference with iree-run-trace as it embeds each input each call so each call gets the right input (or the wrong input). I modified one of the yaml files to simulate what you're doing at the python level but was not able to reproduce it. Modification is here: https://gist.github.com/benvanik/53a745b90e28134753ae6389cd3c4364

**Comment by benvanik** [comment]
(if there's a bug here I really want to fix it and appreciate the help, but am currently stuck without a reproducer and my psychic debugging is not working :)

**Comment by jpienaar** [comment]
I'll try and see if I can repro tomorrow (trying to scan thread quickly)

**Comment by benvanik** [comment]
Thanks @jpienaar! I'd probably start at the python level so we can verify the call traces as we go. Happy to pair up on it when we get something! According to sogartar the x86-64/local-task config was used but looking at one of the dumps the vmfb is actually compiled for vulkan - so I have no idea what's going on or what the original environment was. If it really does reproduce on both CPU and Vulkan that really helps things as it should also reproduce on CUDA and it eliminates _most_ of codegen (but not linalg/bufferization-level).

Brain dump:

I think the most salient things to try are running it with/without `--device_allocator=debug`, with/without `--device_allocator=caching`, and with/without `--device_allocator=caching --device_allocator=debug`. If we can fill out that matrix it'll help narrow down what's happening and then if it's not something obvious we can dogfood the new trace replay stuff to ensure we can more easily triage things like this in the future.

My first thought was that we were generating code assuming that buffers were zeroed as without the caching allocator they almost always are and it'd be hard to spot. I added the `debug` allocator which scribbles all memory that's allocated and that should be able to rule out such issues irrespective of the caching allocator as no buffer our generated code sees will ever start zeroed.

My next thought was that there was some state leak somewhere causing buffers to remain in use by two places that both thought they had unique buffers but after an audit I couldn't find out how that's possible in the runtime side (though it may be possible in the python side!). The trace replay tool should be able to reproduce that kind of issue (you can make multiple calls with the same buffers and chain buffers between calls, simulating the reuse the python layer is doing) but I couldn't get it to happen. TSAN may help here if we can get a reproducer or run the original stuff with it enabled (doubtful in python land).

My next thought was that this was unique to the set_params behavior in this example - the model includes constants but then they get overridden with the external values. Looking at the program we generate, though, this seems unlikely as it's embarrassingly bad (whoops) and copies in the set_params args every invocation such that there shouldn't be any way for future changes to the params to impact model execution.

Finally, I got suspicious that this may be target dependent. I'm on an AMD CPU and don't enable host features so it's possible this relates to a codegen bug that only triggers on certain archs. For example if some crazy masking/padding/etc path kicks in on certain vector widths and doesn't properly restrict its range if it started seeing non-zero values it may produce the wrong results. I don't know what machine the original was run on though or its configuration. <<this is the moment where I cracked open the posted vmfbs and noticed one was CPU/one was Vulkan.... 🍺>>

**Comment by sogartar** [comment]
Here are dumps from the test matrix as @benvanik suggested [stateful_model_test_dump_matrix.zip](https://github.com/openxla/iree/files/10937784/stateful_model_test_dump_matrix.zip)

One curious thing I noticed in the dumps is that the input to `set_params` on the second call is different! This should not happen. In the test `set_params` is always passed the same thing.

**Comment by dellis23** [comment]
I think I'm getting different results from you @sogartar.

| Command                                                                                         | Result  |
|-------------------------------------------------------------------------------------------------|---------|
| python ./tests/e2e/models/stateful_model_test/stateful_model_test.py --allocators               | Passed  |
| python ./tests/e2e/models/stateful_model_test/stateful_model_test.py --allocators debug         | Passed* |
| python ./tests/e2e/models/stateful_model_test/stateful_model_test.py --allocators caching debug | Failed  |
| python ./tests/e2e/models/stateful_model_test/stateful_model_test.py --allocators caching       | Failed  |

(`*` result differs from the result in [stateful_model_test_dump_matrix.zip](https://github.com/openxla/iree/files/10937784/stateful_model_test_dump_matrix.zip))

Not sure if that's a clue.  Platform information:

```
$ uname -a
Linux daniel.hostname 5.19.11-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1rodete1 (2022-10-31) x86_64 GNU/Linux
````

**Comment by dellis23** [comment]
I ran the same matrix without Python by 1) saving the vmfb generated [here](https://github.com/nod-ai/SHARK-Runtime/blob/9a2956ee81a97f299c91ee75ce1bcb881b0872a6/tests/e2e/models/stateful_model_test/stateful_model_test.py#L24-L30), 2) unzipping the input / output npz files, and 3) running it all through `iree-run-module`.  It passed everywhere:

```shell
$ iree-run-module --module=stateful_model.vmfb --function=forward --input=@input.npy --expected_output=@output.npy
EXEC @forward
[SUCCESS] all function outputs matched their expected values.
$ iree-run-module --module=stateful_model.vmfb --function=forward --input=@input.npy --expected_output=@output.npy --device_allocator=caching
EXEC @forward
[SUCCESS] all function outputs matched their expected values.
$ iree-run-module --module=stateful_model.vmfb --function=forward --input=@input.npy --expected_output=@output.npy --device_allocator=debug
EXEC @forward
[SUCCESS] all function outputs matched their expected values.
$ iree-run-module --module=stateful_model.vmfb --function=forward --input=@input.npy --expected_output=@output.npy --device_allocator=debug --device_allocator=caching
EXEC @forward
[SUCCESS] all function outputs matched their expected values.
```

**Comment by dellis23** [comment]
Alright, based on the discussion I'm not sure the extent to which this is known, but I found something interesting: calling `module.set_params(*params)` **twice** appears to be the root of the problem.  If I move this call outside of the `range` loop such that it only executes once, the tests pass.

Also, I tried sanity checking your statement @sogarter that params was different each time you set it.  Where did you see / test this?  I tried dumping every individual param float value at the test script level and comparing across invocations, and I found them to be the same both times.

Edit: although this all makes me realize: how is `iree-run-module` able to successfully execute this and get the correct results without setting the parameters from the parameters file?

**Comment by sogartar** [comment]
> Also, I tried sanity checking your statement @sogarter that params was different each time you set it. Where did you see / test this? I tried dumping every individual param float value at the test script level and comparing across invocations, and I found them to be the same both times.

@dellis23, in the `calls.yaml` dump. You should see this if you do a diff between the case of the default allocator and the caching+debug allocator.

**Comment by dellis23** [comment]
I eyeballed them and they looked the same regardless of which call.  I wrote a quick script to validate:

```python
import yaml

files = """./with_default_allocator_good/calls.yaml
./with_debug_allocator/calls.yaml
./with_caching_debug_allocator_bad/calls.yaml
./with_caching_allocator/calls.yaml"""

files = files.split('\n')

for file_ in files:
  with open(file_, 'r') as f:
    data = yaml.load_all(f, Loader=yaml.Loader)
    for i, doc in enumerate(data):
      if 'function' not in doc or doc['function'] != 'iree_jax.set_params':
        continue
      hash_ = hash(doc['args'][0]['contents'])
      print(f"Filename {file_}, document #{i}, params hash {hash_}")
```

This gives the following result:

```shell
$ python diff-calls.py
Filename ./with_default_allocator_good/calls.yaml, document #3, params hash 2814887096851878538
Filename ./with_default_allocator_good/calls.yaml, document #5, params hash 2814887096851878538
Filename ./with_debug_allocator/calls.yaml, document #3, params hash 2814887096851878538
Filename ./with_debug_allocator/calls.yaml, document #5, params hash 2814887096851878538
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, params hash 2814887096851878538
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, params hash 2814887096851878538
Filename ./with_caching_allocator/calls.yaml, document #3, params hash 2814887096851878538
Filename ./with_caching_allocator/calls.yaml, document #5, params hash 2814887096851878538
```

This was based off of [this](https://github.com/openxla/iree/files/10937784/stateful_model_test_dump_matrix.zip) ZIP file.

**Comment by sogartar** [comment]
@dellis23, I think you are taking just the first argument with
```Python
hash_ = hash(doc['args'][0]['contents'])
```
The function has multiple arguments.

**Comment by dellis23** [comment]
Ah you're right, thanks.

```$ python diff-calls.py
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #0, params hash 208940184091512603
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #1, params hash 738060328589878804
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #2, params hash 3446267229797925391
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #3, params hash -1644573840268385573
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #4, params hash 976501328854964811
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #5, params hash -8766845304419410441
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #6, params hash 1035683000506465608
Filename ./with_default_allocator_good/calls.yaml, document #3, arg #7, params hash -4582869004155070815

Filename ./with_default_allocator_good/calls.yaml, document #5, arg #0, params hash 208940184091512603
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #1, params hash 738060328589878804
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #2, params hash 3446267229797925391
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #3, params hash -1644573840268385573
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #4, params hash 976501328854964811
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #5, params hash -8766845304419410441
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #6, params hash 1035683000506465608
Filename ./with_default_allocator_good/calls.yaml, document #5, arg #7, params hash -4582869004155070815

Filename ./with_debug_allocator/calls.yaml, document #3, arg #0, params hash 208940184091512603
Filename ./with_debug_allocator/calls.yaml, document #3, arg #1, params hash 738060328589878804
Filename ./with_debug_allocator/calls.yaml, document #3, arg #2, params hash 3446267229797925391
Filename ./with_debug_allocator/calls.yaml, document #3, arg #3, params hash -1644573840268385573
Filename ./with_debug_allocator/calls.yaml, document #3, arg #4, params hash 976501328854964811
Filename ./with_debug_allocator/calls.yaml, document #3, arg #5, params hash -8766845304419410441
Filename ./with_debug_allocator/calls.yaml, document #3, arg #6, params hash 1035683000506465608
Filename ./with_debug_allocator/calls.yaml, document #3, arg #7, params hash -4582869004155070815

Filename ./with_debug_allocator/calls.yaml, document #5, arg #0, params hash 208940184091512603
Filename ./with_debug_allocator/calls.yaml, document #5, arg #1, params hash 738060328589878804
Filename ./with_debug_allocator/calls.yaml, document #5, arg #2, params hash 3446267229797925391
Filename ./with_debug_allocator/calls.yaml, document #5, arg #3, params hash -1644573840268385573
Filename ./with_debug_allocator/calls.yaml, document #5, arg #4, params hash 976501328854964811
Filename ./with_debug_allocator/calls.yaml, document #5, arg #5, params hash -8766845304419410441
Filename ./with_debug_allocator/calls.yaml, document #5, arg #6, params hash 1035683000506465608
Filename ./with_debug_allocator/calls.yaml, document #5, arg #7, params hash -4582869004155070815

Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #0, params hash 208940184091512603
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #1, params hash 738060328589878804
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #2, params hash 3446267229797925391
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #3, params hash -1644573840268385573
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #4, params hash 976501328854964811
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #5, params hash -8766845304419410441
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #6, params hash 1035683000506465608
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #3, arg #7, params hash -4582869004155070815

Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #0, params hash 208940184091512603
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #1, params hash -8766845304419410441
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #2, params hash 5183134544446051955
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #3, params hash -1644573840268385573
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #4, params hash 3446267229797925391
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #5, params hash 738060328589878804
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #6, params hash 1035683000506465608
Filename ./with_caching_debug_allocator_bad/calls.yaml, document #5, arg #7, params hash -4582869004155070815

Filename ./with_caching_allocator/calls.yaml, document #3, arg #0, params hash 208940184091512603
Filename ./with_caching_allocator/calls.yaml, document #3, arg #1, params hash 738060328589878804
Filename ./with_caching_allocator/calls.yaml, document #3, arg #2, params hash 3446267229797925391
Filename ./with_caching_allocator/calls.yaml, document #3, arg #3, params hash -1644573840268385573
Filename ./with_caching_allocator/calls.yaml, document #3, arg #4, params hash 976501328854964811
Filename ./with_caching_allocator/calls.yaml, document #3, arg #5, params hash -8766845304419410441
Filename ./with_caching_allocator/calls.yaml, document #3, arg #6, params hash 1035683000506465608
Filename ./with_caching_allocator/calls.yaml, document #3, arg #7, params hash -4582869004155070815

Filename ./with_caching_allocator/calls.yaml, document #5, arg #0, params hash 208940184091512603
Filename ./with_caching_allocator/calls.yaml, document #5, arg #1, params hash -8766845304419410441
Filename ./with_caching_allocator/calls.yaml, document #5, arg #2, params hash 5183134544446051955
Filename ./with_caching_allocator/calls.yaml, document #5, arg #3, params hash -1644573840268385573
Filename ./with_caching_allocator/calls.yaml, document #5, arg #4, params hash 3446267229797925391
Filename ./with_caching_allocator/calls.yaml, document #5, arg #5, params hash 738060328589878804
Filename ./with_caching_allocator/calls.yaml, document #5, arg #6, params hash 1035683000506465608
Filename ./with_caching_allocator/calls.yaml, document #5, arg #7, params hash -4582869004155070815
```

It's interesting that it's only a consistent subset of the parameters that are changed.

**Comment by dellis23** [comment]
I just went back and tested again that all of the parameters are the same when we call `module.set_params` via Python and they are (I was previously only testing the first parameter).

Also, if I remove the set_params call altogether, everything works.  This makes sense, since I see parameters embedded in the mlir for the model.  It also explains why `iree-run-module` works.

Is there any way we can easily reproduce the two calls to `set_params` and one call to `forward` using something like `iree-run-module` (or can we batch all of these together in the same invocation)?  Otherwise it seems like we might need to write a C repro, which I'm not super fluent in.

**Comment by jpienaar** [comment]
Ben recently added stateful support in the run scripts (ai think that's linked above, else it's from past 10 days) that allows one to have a "blackboard" where params are set and read from that could help here.

**Comment by powderluv** [comment]
Is the call to `module.set_params(*params)` twice an error in how we are using the Python API ?

**Comment by dellis23** [comment]
> Is the call to `module.set_params(*params)` twice an error in how we are using the Python API ?

It doesn't seem strictly necessary here, but the call should be idempotent if the same values are passed in, no?

**Comment by sogartar** [comment]
`module.set_params(*params)` is setting the values with what is already in the model. It should not change anything. These calls are critical in reproducing the problem. Without them I can't reproduce.

**Comment by dellis23** [comment]
Alright, I believe I've found the root cause.  A few things to note:

1) The values themselves are not actually changing.  For example, in the list of hashed contents I posted [above](https://github.com/openxla/iree/issues/12161#issuecomment-1464502638), where the contents seem to change to incorrect values, it's actually the case that we are pointing to the wrong buffers altogether.

2) This incorrect pointer is grabbed inside [`iree_hal_caching_allocator_pool_find_and_take_buffer`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L169).  If all of the params were of different size, or we scanned in the same order, we would potentially "accidentally" grab the correct values.  Because we scan in reverse order and we see a buffer of the same size as another parameter, we end up grabbing the wrong buffer and returning it.

3) Wouldn't this mean rather than values changing, we'd likely see at least one swap places?  Yup!  If you look back to the list of hashed contents I posted [above](https://github.com/openxla/iree/issues/12161#issuecomment-1464502638), you'll see some of the values (e.g. `738060328589878804`) don't just disappear in the bad runs -- they change places.  Too many numbers or we might have noticed earlier!

The language around "free" and the logic we're applying to determine whether to return the buffer seems incorrect at [this stage](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L165) (e.g. doing fairly coarse checks such as whether the buffer is the right size).  It doesn't seem like these buffers should be "free" at all (we're still using them, after all); also, it seems semantically like we are wanting to find an existing buffer, not a free one.

That being said, I don't know enough about how this is intended to work to know whether this is actually wrong at a higher level (and if it is, what the correct calls would be).  If someone (presumably @benvanik) can validate whether my intuition here is correct and what we probably _should_ be doing instead, I can look into it more and try to get a fix.  Also happy to report back any tracebacks or logic flows that got me to a particular place if that's easier than reproducing on your own.

**Comment by benvanik** [comment]
This is really useful information @dellis23 - thanks for digging in - I don't think any of us noticed the data changes you point out!

RE iree_hal_caching_allocator_pool_find_and_take_buffer, I'm not sure I follow - can you clarify what you mean by "incorrect pointer" and "wrong buffer" - the only things that classify a "correct buffer" are its type, usage, and size, and any buffer matching those 3 things is correct.

RE "free" I'm also not sure I follow - the list only tracks buffers that are free for use (or should), so it's a free list - any buffer in that list should definitely not be in use. iree_hal_caching_allocator_pool_take_buffer_at (called by iree_hal_caching_allocator_pool_find_and_take_buffer) removes the buffer it takes from the list because it's in use, and the only thing that (should) add it back to the list is iree_hal_caching_allocator_pool_push_buffer that gets called when the buffer is released back to the pool when it is no longer in use.

I'm still not sure I see the bug (but don't doubt there is one).

**Comment by benvanik** [comment]
One thing to try now that you're debugging at this level would be to print out the buffers as they are acquired/released to the free list - if you see two acquires without a release or something that'd indicate what you're talking about above (I think?) and would be incorrect, but if they're all perfectly paired (acquire A acquire B release A release B etc) then that's likely not the issue.

**Comment by dellis23** [comment]
Phew.  I've investigated seemingly every relevant twist and turn here and tried to boil it down to the essential.  I think I understand the intent of the allocator and how this flow should work now.  It wasn't clear to me whether the allocator was intended to re-use these same Python buffers and their respective values across calls, or whether it was to do something simpler.  I'm pretty sure the former isn't true, and it probably made my message above confusing.

# The First Call to `set_params`

Everything starts with the call to `set_params` in Python.  Since this is a function defined in the model, we go through [`FunctionInvoker.__call__`](https://github.com/openxla/iree/blob/e87f194f3e36ae20cbf94ea075765221e67b3850/runtime/bindings/python/iree/runtime/function.py#L113).  After setting up the invocation context, we [pack the arguments](https://github.com/openxla/iree/blob/e87f194f3e36ae20cbf94ea075765221e67b3850/runtime/bindings/python/iree/runtime/function.py#L115).  This is where the data structures that ultimately cause trouble are initialized.

Across the boundary from Python into C++, we enter [`Pack`](https://github.com/openxla/iree/blob/e87f194f3e36ae20cbf94ea075765221e67b3850/runtime/bindings/python/invoke.cc#L593).  Inside `Pack`, we loop through the individual positional arguments and [call into the packing function](https://github.com/openxla/iree/blob/e87f194f3e36ae20cbf94ea075765221e67b3850/runtime/bindings/python/invoke.cc#L613) on that argument.  This packing function resolves down to [`GetGenericPackCallbackForNdarray`](https://github.com/openxla/iree/blob/e87f194f3e36ae20cbf94ea075765221e67b3850/runtime/bindings/python/invoke.cc#L381).  Here, we [call out](https://github.com/openxla/iree/blob/e87f194f3e36ae20cbf94ea075765221e67b3850/runtime/bindings/python/invoke.cc#L401) to `AllocateBufferCopy`.  This goes through [vtable dispatch via `iree_hal_allocator_allocate_buffer`](https://github.com/openxla/iree/blob/97779d7f494660f88864b035475ec77a1e54c6c8/runtime/src/iree/hal/allocator.c#L217) to bring us to the caching allocator's [`iree_hal_caching_allocator_allocate_buffer`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L688) function.

Next, we [call to `iree_hal_caching_allocator_pool_acquire`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L752-L754), which [calls into `iree_hal_caching_allocator_pool_find_and_take_buffer`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L248-L253) (definition [here](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L169)).  For each of our 8 arguments in this first call, we fall through with a NULL value.  This causes `existing_buffer` to evaluate as false, and we avoid taking [the branch that would exit the function](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L260-L265). Next, since no existing buffer was found, [we copy `initial_data` into the buffer](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L283-L285).  This all works as expected.

Once `set_params` exits, the ref count for our argument list drops to 0 and the list is released.  This ultimately causes [`iree_vm_list_destroy`](https://github.com/openxla/iree/blob/af60bfbfeeffbc56fbf6cc41b6af12e0842edc4b/runtime/src/iree/vm/list.c#L236) to be called, which ultimately calls [`iree_hal_caching_allocator_pool_release`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L305) on the items in the list.

# The Second Call to `set_params`

Everything proceeds the same as in the first call until we get to [`iree_hal_caching_allocator_pool_find_and_take_buffer`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L169).  Unlike the first example, we now no longer fall through for each argument.  Instead, the caching allocator finds an appropriate buffer that was released earlier and returns it.  Upstream, this causes the [check for `existing_buffer`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L260-L265) to evaluate as `true` now, and we return.

There's a problem though: because we exited the function early, we never [copied in `initial_data`](https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L282-L286); this means we're just re-using data from earlier.  Since some of our parameters' buffers look the same from the caching allocator's point of view, and we're iterating in reverse order, the allocator ends up choosing a buffer that was previously assigned to a different parameter (what I called the "wrong" buffer earlier), causing parameter values to be swapped.

Based on the intention of the allocator, I now see that the buffer choice isn't wrong per se; it's just that we need to then fill the buffer with `initial_data`, if passed.

Does this look right to you @benvanik?

**Comment by stellaraccident** [comment]
Thank you, Daniel - I think you've identified the bug. Thank you for taking the time to understand how all of this works through the Python layer.

Indeed, I'm not seeing where anything would be handling the initial data in the found case. This likely doesn't happen much (or at all) in the steady state of operation but just at these edges (https://github.com/openxla/iree/blob/689e0fa332fda93404462636fa60fdaf96486aa8/runtime/src/iree/hal/utils/caching_allocator.c#L260).

**Comment by benvanik** [comment]
![image](https://user-images.githubusercontent.com/75337/225691608-83445a74-f3b3-4fb1-ae06-2fa6495b7fdd.png)

you are absolutely correct and that's the ticket! I'll get this fixed now!

**Comment by dellis23** [comment]
Awesome! That was a fun one :-)

**Comment by benvanik** [comment]
Fix in #12660 (but would be good to confirm). This wouldn't show in our native tools as we never initialize inputs using initial_data and instead allocate the buffers and map them in order to parse the strings/load npy files/etc in-place. That at least makes me feel better about having not been able to reproduce it but also means we _really_ need the HAL CTS to get some attention. That is where we should be catching these issues :(

**Comment by benvanik** [comment]
Merged now - please let me know if there are still issues!

**Comment by sogartar** [comment]
I tried out the test and it is working OK now.
Does it make sense to add this to the auto tests?
