### ISSUE TITLE
Injecting a custom dispatch pass after iree-linalg-strategy-decompose-pass

### ISSUE THREAD

**Issue by c-rhodes** [iree-org/iree#12283]
Hi, as @benvanik suggested on [Discord](https://discord.com/channels/689900678990135345/689932666505920596/1075525532827009044) I've attached a print-after-all dump. The input is taken from one of our pipelines:
```
module {
  func.func @pipeline(%arg0: tensor<1080x1932x1xi32>) -> (tensor<1080x1920x1xi32>) {
    %cst_10 = arith.constant dense<[[[1],[2],[3],[4],[5],[6],[7],[6],[5],[4],[3],[2],[1]]]> : tensor<1x13x1xi32>
    %c0_i32 = arith.constant 0 : i32
    %21 = tensor.empty() : tensor<1x1080x1920x1xi32>
    %148 = linalg.fill ins(%c0_i32 : i32) outs(%21 : tensor<1x1080x1920x1xi32>) -> tensor<1x1080x1920x1xi32>
    %36 = tensor.expand_shape %arg0 [[0, 1], [2], [3]] : tensor<1080x1932x1xi32> into tensor<1x1080x1932x1xi32>
    %149 = linalg.depthwise_conv_2d_nhwc_hwc {dilations = dense<1> : tensor<2xi64>, strides = dense<1> : tensor<2xi64>} ins(%36, %cst_10 : tensor<1x1080x1932x1xi32>, tensor<1x13x1xi32>) outs(%148 : tensor<1x1080x1920x1xi32>) -> tensor<1x1080x1920x1xi32>
    %39 = tensor.collapse_shape %149 [[0, 1], [2], [3]] : tensor<1x1080x1920x1xi32> into tensor<1080x1920x1xi32>
  return %39 : tensor<1080x1920x1xi32>
  }
}
```

My pass injecting the custom dispatch logic (**Stream dialect**) is `iree-linalg-conv-to-kernel`. It replaces a `linalg.depthwise_conv_1d_nwc_wc` op with `flow.dispatch` op calling a kernel. It's ran after `iree-linalg-strategy-decompose-pass` such that the 2d convolution has been decomposed into a 1d conv on which it operates.

Integrating the pass at this point in the pipeline is leading to a bunch of issues that's making me question if it's feasible. The first error (from **iree-convert-to-llvm**) is`conv2d-examples/1080p_horizontal/1_13_1080_1920_1_hwc.mlir:8:12: error: failed to legalize operation 'func.func' that was explicitly marked illegal`. The pass is inserting ops from the func dialect which are illegal in **iree-convert-to-llvm**. I noticed **iree-vm-conversion** pass converts `func.func` -> `vm.func` but this pass is ran earlier in the pipeline. I tried running this pass after the pass I added which fixes this particular issue, but hit another error and so on.

I'd just like to understand if what I'm trying to do is feasible or if there's a better approach?

I also have a version with HAL dialect I could share.

Let us know if you need anything else, and thanks in advance!

[1_13_1080_1920_1_hwc.kernel.print.after.all.txt](https://github.com/iree-org/iree/files/10783395/1_13_1080_1920_1_hwc.kernel.print.after.all.txt)

**Comment by benvanik** [comment]
I think you're doing something out of order - you're creating flow.dispatch ops _inside_ of a dispatch which isn't supported (maybe one day we can have nested dynamic parallelism, but not today :).

There are two paths for custom device code. One is to swap out ops at the frontend and have those tiled automatically - that'll be useful for hand-authored code or externally-defined microkernels you want to target specifically. The other is to turn ops inside of dispatches into external calls during codegen. I think your LinalgConvToKernelPass is doing the first style (creating dispatches) but doing it at the location where the second style goes (swapping with calls) causing issues. Since you can turn linalg.depthwise_conv_1d_nwc_wc into your call then it should be as simple as replacing that with a func.call (+ the func.func declaration) where you are instead of doing anything with dispatch ops.

This second path will get easier with the work on #12292 to make injecting codegen passes easier. There's an idea for how we can expose microkernels to the frontend to make the first path possible to fuse/tile/distribute microkernels and that'd make it easier to define custom calls all the way from the tosa/linalg input level.

**Comment by c-rhodes** [comment]
Thanks for clarifying. It sounds like replacing 2d convs in the frontend is the extent of this pass then. I'll have a look at calling these kernels as externals calls instead for 1d ops. I guess this is a standard MLIR mechanism and not special to IREE like custom dispatch? If you could point me to any examples I would appreciate that.

Thanks for your help!

**Comment by benvanik** [comment]
Doing it in the frontend isn't yet wired up - that'll require #12300 - but doing it where you're doing it now should work ala custom_dispatch. So instead of turning your conv op into a dispatch you just turn it into a func.call and declare the func.func just like custom_dispatch does. I'd recommend doing that for now until the other ways get more support.

**Comment by c-rhodes** [comment]
Sorry by frontend I meant the similar pass I have that operates on 2d convs and is run really early in the pipeline alongside the InputConversion passes (briefly mentioned it on Discord). That does work.

**Comment by benvanik** [comment]
Does it? We may be talking about different things :) If you have something working then that's great!

**Comment by allieculp** [comment]
@c-rhodes Is this issue still open?

**Comment by c-rhodes** [comment]
It can be closed now, thanks all!
