### ISSUE TITLE
Reference to iree-org in run_module_app/build_apk.sh

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#12318]
https://github.com/openxla/iree/blob/main/tools/android/run_module_app/build_apk.sh still has a reference to "iree-org" on https://github.com/openxla/iree/blob/bdd679dd90f86121762520de6f0022cf696f869c/tools/android/run_module_app/build_apk.sh#L248. It appears to be referencing a directory created in a previous step, but it's not clear how this directory got the iree-org name. Could you please update this as appropriate for the repository move?

**Comment by ScottTodd** [comment]
Oh... I updated this in the `google` -> `iree-org` move also: https://github.com/openxla/iree/commit/7df397317736788046e02e5d8e821c498d7266da#diff-ffaab20f9b0bc25741720a0a5e03769740c12b7e6df7a7470437e50b281dbb77

**Comment by GMNGeoffrey** [comment]
Aaaah. I think that might have been a mistake as well. Does this script even work anymore?

**Comment by allieculp** [comment]
Bumping up - is this still open?

**Comment by ScottTodd** [comment]
Yes, this issue is still open.

@antiagainst do you think we could just delete https://github.com/openxla/iree/tree/main/tools/android/run_module_app ? Does it still work? That was added back in 2020 but has only been kept up to date with global find/replace changes. We could also move it to the [iree-samples repo](https://github.com/iree-org/iree-samples).
