### ISSUE TITLE
Fix TorchInductor Dependency Issue

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#12457]
### Request description

To get Torch Inductor working in SHARK, we need to reinstall torch using:

```
pip install numpy --pre torch[dynamo] --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117
```

And uncomment the line:

```
#frontend_model = torch.compile(frontend_model, mode="max-autotune", backend="inductor")
```

in shark/shark_benchmark_runner.py

This is needed because in order to satisfy the dependency requirements of `torch-mlir`, `setup_venv.sh` installs a version of torch and pytorch-triton that is out of date. We end up needing 2 virtual environments: 1 to run the PyTorch imports and another to benchmark with TorchInductor.

### What component(s) does this issue relate to?

Other

**Comment by ScottTodd** [comment]
Is this still an issue? Things on the PyTorch / SHARK side have changed quite a bit since this was filed (e.g. https://github.com/nod-ai/SHARK-Turbine).

If this related to https://github.com/openxla/iree/blob/main/.github/workflows/run_shark_tank.yml , that workflow hasn't been running for quite some time: https://github.com/openxla/iree/actions/workflows/run_shark_tank.yml

**Comment by ScottTodd** [comment]
Closing stale issue. This should be tracked in another repo if it still needs work.
