### ISSUE TITLE
Failing tests on macOS

### ISSUE THREAD

**Issue by antiagainst** [iree-org/iree#12496]
This issue tracks failing tests on macOS before disabling them in the [initial bringup of macOS CI](https://github.com/openxla/iree/actions/runs/4320773849/jobs/7541343140#step:7:2325):

```
The following tests FAILED:
	420 - iree/compiler/bindings/c/loader_test (Failed)
	426 - iree/compiler/API/python/test/transforms/ireec/compile_sample_module (Failed)
```

**Comment by miladHakimi** [comment]
Hi @antiagainst,

I ran the tests and figured out that there is a typo here that causes the failure in `compile_sample_module`.

https://github.com/openxla/iree/blob/08ae97f9007c8a54e619f6252dd0962ee63342a6/tools/test/iree-run-module-outputs.mlir#L3-L6

The `--check-prefix=NO-OUTPUT` should be `--check-prefix=NO-OUTPUT-LABEL` to match the label in line 6. 

I tried to fix the other bug with the `loader_test` as well, but I couldn't figure out what is wrong. I ran `ctest` with the `-v` option and inspected the log. It says:
```
IREE COMPILER ERROR: Could not find symbol '_ireeCompilerErrorDestroy'
ERROR: Could not load library
```
I then look at the following CMakeLists.

https://github.com/openxla/iree/blob/08ae97f9007c8a54e619f6252dd0962ee63342a6/compiler/bindings/c/CMakeLists.txt#L43-L65

I suspect there is a problem here but I might be wrong because I don't have a lot of experience with the complex CMake structures. 

I'll send a PR for the first fix.

**Comment by allieculp** [comment]
@antiagainst Please help to add priority and working status here!

**Comment by allieculp** [comment]
@miladHakimi Are there any PRs to attach here? Any update?

**Comment by antiagainst** [comment]
I put this in backlog for now -- don't think we will handle this anytime soon.
