### ISSUE TITLE
FP16 error when close iree-codegen-llvmgpu-enable-transform-dialect-jit

### ISSUE THREAD

**Issue by Yaokbtong** [iree-org/iree#12606]
### What happened?

HI, excuse me. the result of this case is wrong。
module attributes {torch.debug_module_name = "PlaceholderModule"} {
func.func https://github.com/forward(%arg0: tensor<1x14x2000xf16>) -> (tensor<1x14xf16>) {
%10 = mhlo.constant dense<0.000000e+00> : tensor
%208 = mhlo.reduce(%arg0 init: %10) applies mhlo.add across dimensions = [2] : (tensor<1x14x2000xf16>, tensor) -> tensor<1x14xf16>
return %208 : tensor<1x14xf16>
}
}

### Steps to reproduce your issue

1. iree-compile ./test.mlir -o test.vmfb --iree-input-type=mhlo   --iree-hal-target-backends=cuda  --iree-codegen-llvmgpu-enable-transform-dialect-jit=false  --iree-hal-cuda-llvm-target-arch=sm_80

2. iree-run-module  --module=test.vmfb  --device=cuda  --function=forward  --cuda_use_streams=true  --output=-  --input=1x14x2000xf16=3

3. output is all 7316, the correct result is 6000.

**Comment by ThomasRaoux** [comment]
Precision for such large fp16 values will highly depends on the order of operations. When disabling `iree-codegen-llvmgpu-enable-transform-dialect-jit` we will fallback to a serial loop for the reduction and add values in order. Therefore it is equivalent to the code here: https://godbolt.org/z/doeqqqsTx
As you can see the result of such a serial loop will be `7316` because not all integers can be represented with fp16 for such large values. So this is technically the correct value for this operation. 

Note that you may get a different value with `iree-codegen-llvmgpu-enable-transform-dialect-jit` enabled since we re-associate operations in order to optimize for runtime performance. 
To calculate such values you want to increase the precision and use float32.

**Comment by sun2011yao** [comment]
Understood, thank you very much for your reply
