### ISSUE TITLE
Attention slicing isn't lowering memory usage like it should

### ISSUE THREAD

**Issue by gpetters94** [iree-org/iree#12655]
### What happened?

I'm working on Stable Diffusion, lowering it through Torch-MLIR from a PyTorch model. The model has a tunable parameter called attention slicing which splits the batch matmul for the attention heads into several separate batch matmuls that are run in sequence as seen [here](https://github.com/huggingface/diffusers/blob/ae4112d2bbfa363f2f3049daad54f0fb89c34499/src/diffusers/models/attention.py#L611). When I lower this to Linalg and run it through IREE-Runtime, however, I'm not seeing any significant memory savings. I've written and attached an isolated test case and while there is some change in memory usage, it is very small.

What my coworkers and I suspect is happening is that IREE-Runtime is running the dispatches in parallel or some other kind of optimization that is "undoing" the attention slicing. How can we ensure that IREE-Runtime runs this code the same way it does in PyTorch or, barring that, how can we make IREE-Runtime run in a memory-conscious way? Is there some way to set a memory cap so that the runtime will sacrifice some speed for memory usage?

### Steps to reproduce your issue

1. Run `iree-compile --iree-input-type=tm_tensor --iree-hal-target-backends=llvm-cpu --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 sliced.mlir -o sliced.vmfb`.
2. Run `iree-benchmark-module --module=sliced.vmfb --device=local-task --function=forward --input=128x640x640xf32 --input=128x640x640xf32 --input=128x640x640xf32`.
3. Repeat for the unsliced variant.
4. Compare the memory usage.

### What component(s) does this issue relate to?

Runtime

### Version information

0cdfe9888d4f6544bc182c09cac1538285452d80

**Comment by gpetters94** [comment]
[Here](https://gist.github.com/gpetters94/8d1059b4d48609d7f217c6ea218934bb) is the benchmarking info for the unsliced test case, and [here](https://gist.github.com/gpetters94/ce2eb9d20dd15b782105e6fafdce517e) is the sliced one.

**Comment by gpetters94** [comment]
Oh, and [here](https://gist.github.com/gpetters94/b4dc216ef1d471854a60a1088cbf95f8) is the script used to generate those just in case.

**Comment by benvanik** [comment]
There's a few things that could be happening; the most likely one can be isolated with `--iree-stream-partitioning-favor=min-peak-memory` and if that makes no real difference then it's likely something with fusion. But I suspect that's it. We default to `--iree-stream-partitioning-favor=max-concurrency`.

It'll be a losing battle to try to get any framework to match any other framework exactly with such high-level inputs as what's an optimization in one may be a pessimization in another. By splitting like this you've said "hey compiler, we have a tremendous amount of independently/concurrently executable work" and IREE happens to be taking advantage of that by assuming your intent was to execute that work fast. Of course, if what you care about more is peak memory consumption then that is the wrong assumption for the compiler to make, but it doesn't know that :)

20% savings seems nice, but what are you targeting?

fyi if you pass `--print_statistics` to iree-benchmark-module it should show you peak/churn for what we allocate - it's a much less noisy number as it only includes the allocations influenced by the compiler instead of application stuff.

**Comment by powderluv** [comment]
Currently without attention slicing we use about ~7GB of VRAM and the goal is to try and support the 4GB cards so if we can split it to get about 3.5GB would be good - so 50% of current usage.

**Comment by benvanik** [comment]
What kind of savings is pytorch seeing? We can compare that with the numbers with min-peak-memory and see how far off we still are.

There's still an entire phase of partitioning we aren't doing where we reorder dispatches to reduce peak usage - depending on the output we see that may be the next lowest-hanging fruit. We may also be missing some dispatch fusion we should have based on the patterns used during splitting and we can verify that we aren't keeping transient tensors live any longer than required.

**Comment by gpetters94** [comment]
It looks like IREE is working as intended after testing with different amounts of slicing: [no slicing](https://github.com/openxla/iree/files/11007110/sl_none.vmfb.txt), [automatic slicing](https://github.com/openxla/iree/files/11007111/sl_2.vmfb.txt), [max slicing](https://github.com/openxla/iree/files/11007112/sl_max.vmfb.txt). Max slicing is seeing savings of ~40% which lines up with PyTorch. It looks like the memory usage oddities we're seeing are unrelated to the attention slicing and that the peak memory usage was misleading.

**Comment by benvanik** [comment]
Yay! You should still give `--iree-stream-partitioning-favor=min-peak-memory` a shot to see if it helps.

**Comment by powderluv** [comment]
Interestingly min-peak-memory is faster on RDNA2 unet by 4ms. It has no effect on RDNA3. All these tests were without attention slicing enabled. Need to do a more controlled study.

https://github.com/nod-ai/SHARK/issues/1202#issuecomment-1474660228
