### ISSUE TITLE
with --mlir-print-ir-after-change, iree doesn't dump the first pass

### ISSUE THREAD

**Issue by mattwalsh** [iree-org/iree#12989]
### What happened?

So if you use the --mlir-print-ir-after-all option, the first thing that is printed is the first pass that is different from the 0th pass.

So if the passes were:
0: Step A
1. Step A
2. Step B
3. Step B
4. Step C
...

Iree will print out stages 2 and 4.  That is, it prints 'after change', but ignores the very first change.  It should print stages 0, 2, and 4.  Otherwise, you never see 'A' nor how 'B' was changed by step 2.

### Steps to reproduce your issue

Something like: iree-run-module --module=some_module -mlir-print-ir-after-all --mlir-print-ir-after-change --function=some_func 

### What component(s) does this issue relate to?

Compiler

**Comment by jpienaar** [comment]
This sounds like a question on LLVM repo rather than here unless this is IREE specific. The first thing printed should be when the output is different from the input (https://github.com/llvm/llvm-project/blob/4624797f816123f327d2c8b80f7ec65c90750024/mlir/lib/Pass/IRPrinting.cpp#L92) rather than output of a pass.

**Comment by ScottTodd** [comment]
Yeah that's all upstream MLIR code.
