### ISSUE TITLE
TF Batch 256 ResNet50 Takes ~4 mins to compile for CUDA

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#13073]
### What happened?

ResNet50 compile time scales linearly with batch size. This is not the case for other models. For Bert-Large and T5-Large below, compile time is similar regardless of batch size.

![image](https://user-images.githubusercontent.com/5143063/231633780-e03715e5-8615-4f38-82be-25efbb2003ba.png)

### Steps to reproduce your issue

1. Download SavedModel: https://storage.googleapis.com/iree-model-artifacts/tensorflow/tf_models_2.12.0_1680491395/RESNET50/batch_256/tf-model.tar.gz

2. Import:
```
iree-import-tf --output-format=mlir-bytecode --tf-import-type=savedmodel_v2 --tf-savedmodel-exported-names=forward <saved_model> -o </path/to/model.mlirbc>
```
3. Compile:
```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=mhlo --iree-hal-cuda-llvm-target-arch=sm_80 </path/to/model.mlirbc> -o </path/to/model.vmfb>
```

### What component(s) does this issue relate to?

Compiler

### Version information

Commit 35bdd9d

**Comment by ThomasRaoux** [comment]
Thanks Marie. We must be missing to tile some batch dimension. @KoolJBlack can you take a first look?

**Comment by KoolJBlack** [comment]
We're unrolling endlessly during `LLVMGPUVectorLoweringPass`. This happens with dispatches that contain convolutions in Resnet, thought the unrolling does not affect the arithmetic of the convolution. I haven't dug into T5 but i suspect like BERT models , it does not contain convolutions which is why their unaffected.

The unrolling issue is caused by `populateVectorBroadcastLoweringPatterns()` and  `vectorToSCFOptions.enableFullUnroll()` during vectorization. 

The first unrolling issue is caused by `populateVectorBroadcastLoweringPatterns()`. It turns this: 
```mlir
  %22 = vector.transfer_read %4[%21], %cst {in_bounds = [true]} : memref<64xf32>, vector<4xf32>
  %23 = vector.broadcast %22 : vector<4xf32> to vector<256x1x4x4xf32>
```
into an endless stream of:
```mlir
    %1814 = vector.load %4[%21] : memref<64xf32>, vector<4xf32>
    %1815 = vector.insert %1814, %cst_0 [0] : vector<4xf32> into vector<4x4xf32>
    %1816 = vector.insert %1814, %1815 [1] : vector<4xf32> into vector<4x4xf32>
    %1817 = vector.insert %1814, %1816 [2] : vector<4xf32> into vector<4x4xf32>
    %1818 = vector.insert %1814, %1817 [3] : vector<4xf32> into vector<4x4xf32>
```

The second issue is `vectorToSCFOptions.enableFullUnroll()` which turns this:
```mlir
  vector.transfer_write %cst_0, %7[%c0, %15, %20, %21] {in_bounds = [true, true, true, true]} : vector<256x1x4x4xf32>, memref<256x112x112x64xf32>
```
into and endless stream of:
```milr
    %22 = vector.extract %cst[0, 0, 0] : vector<256x1x4x4xf32>
    vector.store %22, %7[%c0, %15, %20, %21] : memref<256x112x112x64xf32>, vector<4xf32>
    %23 = affine.apply #map()[%20]
    %24 = vector.extract %cst[0, 0, 1] : vector<256x1x4x4xf32>
    vector.store %24, %7[%c0, %15, %23, %21] : memref<256x112x112x64xf32>, vector<4xf32>
    %25 = affine.apply #map1()[%20]
    %26 = vector.extract %cst[0, 0, 2] : vector<256x1x4x4xf32>
    vector.store %26, %7[%c0, %15, %25, %21] : memref<256x112x112x64xf32>, vector<4xf32>
```

Full gist https://gist.github.com/KoolJBlack/9e3c451ea20344f1810498af3d95cc31

Trying to determine why this only affects convolutions.
