### ISSUE TITLE
Redo micro kernel as macro kernel

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13197]
Need to circle back on this with proposals / updates next week.

**Comment by allieculp** [comment]
Converting this draft to an issue for continued discussion.
@mattwalsh @MaheshRavishankar @sherhut for visibility here.

**Comment by allieculp** [comment]
@mattwalsh @grypp Planning to discuss this issue and next steps at tomorrow's sync. Please add any discussion here until then.

**Comment by benvanik** [comment]
(this has no context - what is this, and what sync will it be discussed at?)

**Comment by grypp** [comment]
I wanted to provide some context and share my opinion.

The microkernels refer to calling a CUDA device function that uses cutlass. We call a microkernel per thread block to process the main loop and epilogue. It is basically the work I implemented in #12026. 

On the other hand, macrokernels refer to calling cutlass for matmul from the host. Once we have implementation of it, it is almost a 0-day work to adapt to new GPU architectures. But it is slower since it disables fusion.

**Pros and Cons of Microkernels:**

- Enables fusion, allowing the result of matmul to be read from registers or shared memory for faster performance.
- For A100 GPUs, microkernels are as efficient as libraries, and they are particularly faster than libraries when fusion is needed (see my talk from all-hands).
- Requires implementing a custom microkernel, which can take time and effort, but definitely less than implementing codegen.
- Not clear what kind of microkernel we need for H100, but Cutlass has gemm for H100.

**Pros and Cons of Macrokernels:**

- Almost 0-day work to adapt to new GPU architectures.
- Slower performance since it disables fusion.

In my opinion, we want macrokernels, why don't we use cuDNN instead of cutlass. cuDNN allows fusion for very primitive things. It is very limitied but it is something.

**Comment by allieculp** [comment]
@grypp @mattwalsh Closing this as we have made decisions on micro kernel. Please re-open if needed.
