### ISSUE TITLE
[CUDA] error: 'func.func' op exceeded GPU memory limit 

### ISSUE THREAD

**Issue by silvasean** [iree-org/iree#13202]
### What happened?

Hitting this error in CUDA compilation:

```
error: 'func.func' op exceeded GPU memory limit of 166912 bytes for function. Got 5767168 bytes
```

[Full error log](https://gist.github.com/silvasean/5b1ad33c9cc0d6d22795be3da9216ef2)

### Steps to reproduce your issue

1. Comment out `.addPass(mlir::createLinalgDetensorizePass)` [here](https://github.com/openxla/iree/blob/e6b7faef0c8c272dd57328039b1290eb321a89dc/compiler/src/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L230) to workaround [this upstream bug](https://github.com/llvm/llvm-project/issues/62249). 

2. Run:

```
iree-compile --iree-hal-target-backends=cuda --iree-input-type=mhlo repro.mlir
```

with [this file](https://gist.github.com/silvasean/b723c571ffa37085a80921dd7dd1ec43). (I didn't reduce this because it seems like it will be pretty obvious which single dispatch region is affected while debugging this, let me know if this is not the case and I can bisect it down)

### What component(s) does this issue relate to?

Compiler

### Version information

iree.git @ 56c4eff7e4ae00a7bbced6e109b566c9f4c213f3

**Comment by aaron-schneider** [comment]
@KoolJBlack can you ptal? Thanks!

**Comment by KoolJBlack** [comment]
The dispatch in question contains a `linalg.generic` as its primary op, but its going down the `LLVMGPUMatmulSimt` pipeline: 
```mlir
hal.executable.variant public @cuda_nvptx_fb, target = <"cuda", "cuda-nvptx-fb", {target_arch = "sm_35"}> {
  hal.executable.export public @_main_dispatch_15_generic_512x4x42x42x64_f32 ordinal(0) layout(#hal.pipeline.layout<push_constants = 3, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer>]>]>) attributes {translation_info = #iree_codegen.translation_info<LLVMGPUMatmulSimt>, workgroup_size = [32 : index, 8 : index, 1 : index]} {
  ^bb0(%arg0: !hal.device, %arg1: index, %arg2: index, %arg3: index, %arg4: index):
    %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg1, %arg2, %arg3, %arg4
    hal.return %x, %y, %z : index, index, index
  }
  builtin.module {
    func.func @_main_dispatch_15_generic_512x4x42x42x64_f32() {
      %cst = arith.constant 1.250000e-01 : f32
      %cst_0 = arith.constant 0.000000e+00 : f32
      %0 = hal.interface.constant.load[0] : i32
      %1 = hal.interface.constant.load[1] : i32
      %2 = hal.interface.constant.load[2] : i32
      %3 = arith.index_castui %0 {stream.alignment = 64 : index, stream.values = [35524672 : index, 240930880 : index, 446337088 : index, 651743296 : index]} : i32 to index
      %4 = arith.index_castui %1 {stream.alignment = 64 : index, stream.values = [57544768 : index, 262950976 : index, 468357184 : index, 673763392 : index]} : i32 to index
      %5 = arith.index_castui %2 {stream.alignment = 64 : index, stream.values = [1728 : index, 36472832 : index, 72943744 : index, 109415936 : index]} : i32 to index
      %6 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%3) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512x42x4x64xf32>>
      %7 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%4) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512x42x4x64xf32>>
      %8 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%5) : !flow.dispatch.tensor<writeonly:tensor<512x4x42x42xf32>>
      %9 = flow.dispatch.tensor.load %6, offsets = [0, 0, 0, 0], sizes = [512, 42, 4, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<512x42x4x64xf32>> -> tensor<512x42x4x64xf32>
      %10 = flow.dispatch.tensor.load %7, offsets = [0, 0, 0, 0], sizes = [512, 42, 4, 64], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<512x42x4x64xf32>> -> tensor<512x42x4x64xf32>
      %11 = tensor.empty() : tensor<512x4x42x42xf32>
      %12 = linalg.fill {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 1, 32, 128, 32]]>} ins(%cst_0 : f32) outs(%11 : tensor<512x4x42x42xf32>) -> tensor<512x4x42x42xf32>
      %13 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d2, d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d1, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction"]} ins(%9, %10 : tensor<512x42x4x64xf32>, tensor<512x42x4x64xf32>) outs(%12 : tensor<512x4x42x42xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 1, 32, 128, 32]]>} {
      ^bb0(%in: f32, %in_1: f32, %out: f32):
        %15 = arith.mulf %in, %in_1 : f32
        %16 = arith.addf %out, %15 : f32
        linalg.yield %16 : f32
      } -> tensor<512x4x42x42xf32>
      %14 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%13 : tensor<512x4x42x42xf32>) outs(%11 : tensor<512x4x42x42xf32>) attrs =  {lowering_config = #iree_codegen.lowering_config<tile_sizes = [[0, 1, 32, 128, 32]]>} {
      ^bb0(%in: f32, %out: f32):
        %15 = arith.mulf %in, %cst : f32
        linalg.yield %15 : f32
      } -> tensor<512x4x42x42xf32>
      flow.dispatch.tensor.store %14, %8, offsets = [0, 0, 0, 0], sizes = [512, 4, 42, 42], strides = [1, 1, 1, 1] : tensor<512x4x42x42xf32> -> !flow.dispatch.tensor<writeonly:tensor<512x4x42x42xf32>>
      return
    }
  }
}
```

The problem with this is its assigning the wrong tile sizes `tile_sizes = [[0, 1, 32, 128, 32]]` to the `linalg.fill` op which results in it not being tiled along the batch dimension. Without tiling, it tries to allocate too much memory and fails. 

I've tested this by forcing it on the `LLVMGPUVectorize`which works fine. I think this is the correct pipeline that should be used here, unless there is a specific reason for this to be on Simt. @ThomasRaoux is out but @okkwon or @manishucsd may know if this is intentional?

**Comment by KoolJBlack** [comment]
Some more things I've discovered. 

As previous comment indicated, this op is taking the `LLVMGPUMatmulSimt` but its not an op we're handling properly. 

This ends up on the simt path since the `linalg.generic` is in kind of a matmul with a reduction along the fastest moving dimension (we don't have named op for this so its written as a generic). Our check for contract ops does not take into consideration reduction dimension. 

We tile with `tile_sizes = [[0, 1, 32, 128, 32]]` which doesn't tile the batch dimension. The code doing this is here: https://github.com/openxla/iree/blame/main/compiler/src/iree/compiler/Codegen/LLVMGPU/KernelConfig.cpp#L263-L267.
I'm not really sure what the logic is here, I'm guessing this is intended to not tile the reduction dimension, but in fact the math is backwards (it affects the batch dimension).

My first approach here was to update all tiled dimensions to 1 (not 0), the op compiles, but further down the line some usual things happen that will negatively affect performance: 
1. GPUVectorization does not activate with this construction. I do not know why. Instead we lower everything to loops seen here: https://gist.github.com/KoolJBlack/bab4dc3d73fa69baf4e92c3b37142954#file-gistfile1-mlir-L1414
2. No shared memory promotion with `LLVMGPUTensorAlloc`

My second attempt was to block `linalg.generic` with reductions from using `LLVMGPUMatmulSimt`.This works for this dispatch, but uploading this to CI results in many other test failures: https://github.com/openxla/iree/pull/13294

I believe the  solution here is to tile the batch dimension. What I cannot figure out is if this shouldn't run on the mamtulsimt pipeline or if there is another way tiling should be done, specifically for the reduction dimension here given the issues I noted above? 

I'm looking for additional input here. @MaheshRavishankar was on blame for the tile calculation with @antiagainst & @hanhanW on review. Could either of you guys comment, specifically on how this IR should be handled?

**Comment by hanhanW** [comment]
I hit a similar issue and fix it in https://github.com/openxla/iree/pull/13304 for CPU side. The idea is setting distribution tile sizes of all other parallel loops to ones. Maybe we can give it a shot?

The first step I'd try is preset the lowering_config, and check the final IR. If it works and this is the fix we want, we can update the logic in KernelConfig.cpp.

**Comment by KoolJBlack** [comment]
Right, I think the CPU solution is what I've tried above here: 
```
  // Tile other partitionable loops with one to avoid unbounded stack
  // allocations.
  for (auto dim : partitionableLoopsOp.getPartitionableLoops(std::nullopt)) {
    if (res[dim] == 0) res[dim] = 1;
  }
```

So the new config for this dispatch would be `tile_sizes = [[1, 1, 32, 128, 32]]`. The issue as I've noted above is this leads to poor IR beyond that I do not think is optimal. I remember in the past discussion around not tiling reduction loops since they're reduced to a single output. Did this affect the CPU side? 

Beyond that, using other pipelines produces correct and much more optimal IR so I need input on which pipeline should be used here.

**Comment by MaheshRavishankar** [comment]
> Right, I think the CPU solution is what I've tried above here:
> 
> ```
>   // Tile other partitionable loops with one to avoid unbounded stack
>   // allocations.
>   for (auto dim : partitionableLoopsOp.getPartitionableLoops(std::nullopt)) {
>     if (res[dim] == 0) res[dim] = 1;
>   }
> ```
> 
> So the new config for this dispatch would be `tile_sizes = [[1, 1, 32, 128, 32]]`. The issue as I've noted above is this leads to poor IR beyond that I do not think is optimal. I remember in the past discussion around not tiling reduction loops since they're reduced to a single output. Did this affect the CPU side?

I dont follow the `tile_sizes` list here. The CPU side is only setting the tile sizes to 1 for parallel loops. So its not tiling reduction loops. 

> 
> Beyond that, using other pipelines produces correct and much more optimal IR so I need input on which pipeline should be used here.

I dont have context on all the CUDA pipelines... I am guessing whichever pipeline is being used, they need to ensure you dont exceed memory usage. So it is a bug in whatever pipeline is being used currently. You can avoid the error by using a different pipeline, but that would not be fixing the core issue.

**Comment by allieculp** [comment]
@KoolJBlack Are you still digging into this issue?

**Comment by KoolJBlack** [comment]
@allieculp yes i'm still investigating

**Comment by antiagainst** [comment]
Sorry late to this due to a bunch of meetings and travels last week. Reading the above, I think it's proper to go down the SIMT pipeline given this is just a matmul, albeit with more parallel dimensions. Likely the SIMT pipeline is hitting issues with such non-canonical matmul forms, which then we need to fix. Check what's breaking in GPUVectorization and such to see what's broken and make them handle such high-D cases too. Or, after tiling and distribute to workgroups, I think you could unroll all remaining parallel dimensions to size 1 to materialize loops. And then inside the loops we should have rank-reduced `linalg.generic` ops with normal matmul (M, N, K) forms. Then the passes should work I think.

**Comment by KoolJBlack** [comment]
Pulling together some conversations here:

@okkwon suggested this dispatch may be the result of a dot general. I haven't been able to line it up from the https://gist.github.com/silvasean/b723c571ffa37085a80921dd7dd1ec43 from sean however. 

@manishucsd and I discussed the actual formation here is a matmul with 2 batch dimensions. The operation: `@_main_dispatch_15_generic_512x4x42x42x64_f32` would line up as  M=42, N=42, K=64 (this is reduced) and the batch dims 512 and 4.  I think this is the appropriate way to think about his here, given the return of `tensor<512x4x42x42xf32>`. This lines up with Lei's latest comment just now. 

I still believe the correct approach is to tile the batch dimension with 1. The math in `KernelConfig.cpp` is incorrect as its unrolling the batch dimension based on the reduction (dimensions are mixed up). I've pushed https://github.com/openxla/iree/pull/13294 which updates the tile sizes here to `[[1, 1, 32, 128, 32]]`. 

From https://github.com/openxla/iree/pull/13294#discussion_r1184024695, @okkwon is suggested a better solution is to reshape the higher order dimensions down to `kNumMaxParallelDims`, so that we just have M, N, K. @antiagainst does this line up with your comment in https://github.com/openxla/iree/issues/13202#issuecomment-1533377374 about `unroll all remaining parallel dimensions to size 1` as well?

I'm trying to workout what this reshape would look like since the two batch dimension on the input are not contagious: 
```
A=tensor<512x42x4x64xf32>
B=tensor<512x42x4x64xf32>
C=tensor<512x4x42x42xf32>
```

Ack the issue with GPUVecotirzation might need a separate fix, but the same issue is related here.

**Comment by MaheshRavishankar** [comment]
We might be trying to solve a pretty hard problem here... general codegen for a einsum like op is very hard (it spans a whole range of regimes of contractions that have totally different solutions). The fact that the batch dimension here is not contiguous gives me a bit of pause. So two paths to take here.

1) I think setting the batch dimensions to 1 is a good approach in general... especially for CUDA.. it increases the parallelism at the block level and there is no reuse on the batch dimension, so that makes sense... this would mean there are no higher than 3 parallel dimensions but those need to be collapse down to 3 or less.

2) It would be good to also see if the `einsum` is a faithful representation of user intent or something that the lowering to stablehlo/linalg is introducing.

**Comment by silvasean** [comment]
> 2\. It would be good to also see if the `einsum` is a faithful representation of user intent or something that the lowering to stablehlo/linalg is introducing.

It is a faithful representation of user intent. See my explanation [here](https://github.com/openxla/iree/issues/12214#issuecomment-1437242844) for why all Transformer-based models will have this (or have an explicit transpose/reshape in them).

**Comment by silvasean** [comment]
I looked into the source code and it is written exactly in the user source code in this way:

```
attn_logits = jnp.einsum('...thd,...Thd->...htT', q, k)
```

https://github.com/deepmind/ferminet/blob/45a8daa2f9ac507d0f033aabe5b7c4526442c33e/ferminet/psiformer.py#L126

**Comment by MaheshRavishankar** [comment]
> I looked into the source code and it is written exactly in the user source code in this way:
> 
> ```
> attn_logits = jnp.einsum('...thd,...Thd->...htT', q, k)
> ```
> 
> [deepmind/ferminet@`45a8daa`/ferminet/psiformer.py#L126](https://github.com/deepmind/ferminet/blob/45a8daa2f9ac507d0f033aabe5b7c4526442c33e/ferminet/psiformer.py#L126)

THanks... @KoolJBlack I think you already implemented setting the batch sizes to 1 right... any issues with landing that?

**Comment by KoolJBlack** [comment]
The patch https://github.com/openxla/iree/pull/13294 solve this specific failure above by tiling the batch dimension (tests and shows improved benchmarks). I believe this fix is needed since there I cannot think of any reason we would not tile a batch dimension on CUDA. 

@okkwon raised a commented about reshaping the parallel and along with Lei's point above. Per my previous comment,  I'm still unclear on how to actually reshape this op to fit within 3 parallel dimension or an MNK representation. Will chat with Lei in a bit. @MaheshRavishankar if you have thought son https://github.com/openxla/iree/pull/13294#discussion_r1184024695 or the PR, do comment thanks.

**Comment by antiagainst** [comment]
Expanding on the possible approaches I said above after chatting with Kojo. Aside from Okwan's [suggestions](https://github.com/openxla/iree/pull/13294#discussion_r1184024695) of performing transposition and collapsing parallel dimensions at the graph level,  1) we could also identify two parallel dimensions as M & N, tile and distribute them to workgroups as usual (what's done right now in matmul pipeline). And then immediately afterwards, have a step to tile (but not distribute) all the remaining parallel dimensions with size 1 and materialize loops in the kernel for them. This would generate `linalg.generic` with LHS and RHS of tensors with non-unit M/N and K, interleaved with some additional unit dims. Invoke patterns to drop those unit dims, and then fold generated collapse/expand shape ops with surrounding tensor extract/insert slices to make tensor extract/insert slices rank reducing. This way we would see `linalg.generic` of the canonical form (M, N, K). So the CodeGen flow should work. 2) We can also extend vectorization and following patterns/passes to be aware of such high-D parallel cases. But that's more involved and harder to solve.

**Comment by MaheshRavishankar** [comment]
> Expanding on the possible approaches I said above after chatting with Kojo. Aside from Okwan's [suggestions](https://github.com/openxla/iree/pull/13294#discussion_r1184024695) of performing transposition and collapsing parallel dimensions at the graph level, 1) we could also identify two parallel dimensions as M & N, tile and distribute them to workgroups as usual (what's done right now in matmul pipeline). And then immediately afterwards, have a step to tile (but not distribute) all the remaining parallel dimensions with size 1 and materialize loops in the kernel for them. This would generate `linalg.generic` with LHS and RHS of tensors with non-unit M/N and K, interleaved with some additional unit dims. Invoke patterns to drop those unit dims, and then fold generated collapse/expand shape ops with surrounding tensor extract/insert slices to make tensor extract/insert slices rank reducing. This way we would see `linalg.generic` of the canonical form (M, N, K). So the CodeGen flow should work. 2) We can also extend vectorization and following patterns/passes to be aware of such high-D parallel cases. But that's more involved and harder to solve.

We dont need to tile by 1 all the non M & N dimensions and have each thread execute the entire batch dimensions for some tile of M, N and K (which is what the above would do). It is better to just tile and distribute them across blocks, so setting the tile size to 1 for those during tile + distribute is probably what we should aim for.. Then we can just eliminate those extra tensor unit dimensions per workgroup using rank-reducing slices and we effectively get a GEMM to pass down the rest of the pipeline.

**Comment by KoolJBlack** [comment]
@rsuderman and I just chatted about this. I'm paraphrasing here, but according to Rob, `dot_general` should not come through the `MHLOToMHLOPreprocessing`. I did a dig through the IR. After this step, all `stablehlo.dot_generals` are removed, however we have the introduction of this einesum call here: 

```mlir
  %161 = mhlo.reshape %160 : (tensor<512x42x256xf32>) -> tensor<512x42x4x64xf32>
  %162 = call @_einsum(%151, %156) : (tensor<512x42x4x64xf32>, tensor<512x42x4x64xf32>) -> tensor<512x4x42x42xf32>
  %163 = mhlo.multiply %162, %19 : tensor<512x4x42x42xf32>
```

This is the einsum source (from Rob): 
```mlir
func.func private @_einsum(%arg0: tensor<512x42x4x64xf32>, %arg1: tensor<512x42x4x64xf32>) -> tensor<512x4x42x42xf32> {
  %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_batching_dimensions = [0, 2], rhs_batching_dimensions = [0, 2], lhs_contracting_dimensions = [3], rhs_contracting_dimensions = [3]>, precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<512x42x4x64xf32>, tensor<512x42x4x64xf32>) -> tensor<512x4x42x42xf32>
  return %0 : tensor<512x4x42x42xf32>
}
```

 But my understanding is this should have been transformed into a `batch _matmul` or `matmul`. According to Rob, this transformation was nuked in this change here: https://github.com/openxla/iree/commit/479900afe1467cd10f349894f758135e54d487e2

@jpienaar @silvasean This may be the source of the problem. The question here is should this conversion have been removed? It might not be redundant as suggested in the PR https://github.com/openxla/iree/pull/13153. If this was active as Sean had suggested earlier during our GPU huddle, we wouldn't be getting these `linalg.generic` this far down the pipe. We already properly handle matmuls and batch matmuls etc. 

Perhaps naïve, but this sounds like the solution Okwan et al are suggesting regarding reshaping this op. We can use what was there and improve upon it if need be?

**Comment by KoolJBlack** [comment]
Ok, this is what the transformation Jacque removed does (from Rob):

```mlir
// -----// IR Dump Before MHLOToMHLOPreprocessing (iree-mhlo-to-mhlo-preprocessing) //----- //
func.func private @_einsum(%arg0: tensor<512x42x4x64xf32>, %arg1: tensor<512x42x4x64xf32>) -> tensor<512x4x42x42xf32> {
  %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_batching_dimensions = [0, 2], rhs_batching_dimensions = [0, 2], lhs_contracting_dimensions = [3], rhs_contracting_dimensions = [3]>, precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<512x42x4x64xf32>, tensor<512x42x4x64xf32>) -> tensor<512x4x42x42xf32>
  return %0 : tensor<512x4x42x42xf32>
}

// -----// IR Dump Before Canonicalizer (canonicalize) //----- //
func.func private @_einsum(%arg0: tensor<512x42x4x64xf32>, %arg1: tensor<512x42x4x64xf32>) -> tensor<512x4x42x42xf32> {
  %0 = "mhlo.transpose"(%arg0) {permutation = dense<[0, 2, 1, 3]> : tensor<4xi64>} : (tensor<512x42x4x64xf32>) -> tensor<512x4x42x64xf32>
  %1 = "mhlo.transpose"(%arg1) {permutation = dense<[0, 2, 3, 1]> : tensor<4xi64>} : (tensor<512x42x4x64xf32>) -> tensor<512x4x64x42xf32>
  %2 = mhlo.reshape %0 : (tensor<512x4x42x64xf32>) -> tensor<2048x42x64xf32>
  %3 = mhlo.reshape %1 : (tensor<512x4x64x42xf32>) -> tensor<2048x64x42xf32>
  %4 = "mhlo.dot_general"(%2, %3) {dot_dimension_numbers = #mhlo.dot<lhs_batching_dimensions = [0], rhs_batching_dimensions = [0], lhs_contracting_dimensions = [2], rhs_contracting_dimensions = [1]>, precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<2048x42x64xf32>, tensor<2048x64x42xf32>) -> tensor<2048x42x42xf32>
  %5 = mhlo.reshape %4 : (tensor<2048x42x42xf32>) -> tensor<512x4x42x42xf32>
  return %5 : tensor<512x4x42x42xf32>
}
```

The final `mhlo.dot_general` looks % 100 like a `linalg.batch_matmul`. I think this is what we want so we should revert the removed patterns?

**Comment by silvasean** [comment]
I ran into this in another model. The user-level einsum is `BTNH,BSNH->BNTS` (also from a transformer attention layer, this one is from the praxis layer library for a large-language model ([code link](https://github.com/google/praxis/blob/368945fb45de619607c9613b876b54b5ef2e58a1/praxis/layers/attentions.py#L1243))).

https://gist.github.com/silvasean/38f7c4c951d6738f1a46f8c5a1072bdc

**Comment by MaheshRavishankar** [comment]
@KoolJBlack lets not get distracted for now. Lets get this working, and worry about performance later. There is a fix that has been discussed. Could we just plumb that through?

**Comment by KoolJBlack** [comment]
Yes, https://github.com/openxla/iree/pull/13294 will fix the crash and happy to commit once approved. 

However, I believe the proper fix to get a performant representation of `dot_general` is to revert the removal of the frontend pattern that implemented the transposes and reshapes. This is whats being discussed in several comments and it already existed hence this new regression. This will require addressing the problem in https://github.com/openxla/iree/issues/13085 without the pattern removal.

**Comment by KoolJBlack** [comment]
https://github.com/openxla/iree/pull/13294 has been merged. 

https://github.com/openxla/iree/issues/13458 is now open for restoring the dot_general lowering. While sean won't hit the lowering issue, I think this issue should remain open until the lowering is back in place.

**Comment by MaheshRavishankar** [comment]
This should be fixed at ToT (by https://github.com/openxla/iree/pull/13468) . @silvasean please verify and close.

**Comment by silvasean** [comment]
Confirmed fixed. Closing.
