### ISSUE TITLE
[Epic] GPU Codegen: Achieve 75% parity with libraries on A100 on Matmul with unaligned shapes with custom codegen

### ISSUE THREAD

**Issue by allieculp** [iree-org/iree#13242]
- [x] #13104

**Comment by allieculp** [comment]
@mattwalsh We might want to consider this closed with the 'soft' landing of unaligned - given the focus shift. WDYT?

**Comment by qcolombet** [comment]
Given the shift of priority, I am inclined to lower the priority of this one.

For the record, what we miss (thanks @nicolasvasilache for the list) is:
- plug the tensorcore scheduling strategy (i.e., we should use `PipeliningSchedulingStrategy::nvidiaTensorCore` instead of `PipeliningSchedulingStrategy::loadGlobalStage0` in this transform https://github.com/openxla/iree/blob/f72ed7933eede0948d03d41f410aaa6f41cacc8f/compiler/src/iree/compiler/Codegen/LLVMGPU/TransformExtensions/LLVMGPUExtensions.cpp#L767), tracked in https://github.com/openxla/iree/issues/13859
- tune tile sizes
- enable mma_sync (we need to have an actual fix for https://github.com/openxla/iree/issues/13451)

**Comment by allieculp** [comment]
@qcolombet I may just close for now given that these were goals created by us which have now changed. Please reopen if you would like!
