### ISSUE TITLE
Compilation hangs with 0-length tensor compilation

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#13347]
The following lax test case fails to compile for the `llvm-cpu` backend.

```
module @jit_lcm {
  func.func public @main() -> (tensor<0xi32> {jax.result_info = ""}) {
    %0 = stablehlo.constant dense<0> : tensor<i32>
    %1 = call @_where(%0) : (tensor<i32>) -> tensor<0xi32>
    return %1 : tensor<0xi32>
  }
  func.func private @_where(%arg0: tensor<i32>) -> tensor<0xi32> {
    %0 = stablehlo.broadcast_in_dim %arg0, dims = [] : (tensor<i32>) -> tensor<0xi32>
    return %0 : tensor<0xi32>
  }
}
```

**Comment by benvanik** [comment]
Can you print-ir-after-all and see roughly where things die? can imagine lots of places not happy with statically-known 0-length tensors (but they'd all be bugs)

**Comment by rsuderman** [comment]
For now I am just triaging failures in lax and trying to build up a bug. Someone in framework integrations can help triage the specific failures.

**Comment by bviyer** [comment]
I briefly looked into it. The issue is happening in `iree-stream-refine-usage` pass. More specifically, the problem statement is in 
```
 %c0 = arith.constant 0 : index
  %0 = stream.async.alloca : !stream.resource<constant>{%c0}
```
It is throwing infinite transfers and thus is hanging in `"mlir::iree_compiler::IREE::Stream::(anonymous namespace)::ApplyStreamableOp<mlir::iree_compiler::IREE::Stream::AsyncAllocaOp>"`

here is a small screen shot of what I am seeing in the debugger:

```
%1 = stream.async.transfer %0 : !stream.resource<constant>{%c0} -> !stream.resource<transient>{%c0}
  %2 = stream.async.transfer %1 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
  %3 = stream.async.transfer %2 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
  %4 = stream.async.transfer %3 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
  %5 = stream.async.transfer %4 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
  %6 = stream.async.transfer %5 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
  %7 = stream.async.transfer %6 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
  %8 = stream.async.transfer %7 : !stream.resource<transient>{%c0} -> !stream.resource<transient>{%c0}
...
```

Commenting out this line (https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Dialect/Stream/Transforms/RefineUsage.cpp#L348) seem to fix the issue. Not sure if this is the right fix.

**Comment by benvanik** [comment]
The reproducer at the top seems to compile just fine for me. @bviyer's test in #13559 does fail, though, and I'll see if I can root cause it. I suspect analysis is getting into an inconsistent state here as it's doing constant -> * -> external and should just have a single transfer inserted but instead seems to generate those transient transfers and that's no good.
