### ISSUE TITLE
MHLOToMHLOPreprocessing missing a dot_general lowering

### ISSUE THREAD

**Issue by NatashaKnk** [iree-org/iree#13458]
### What happened?

MHLOToMHLOPreprocessing used to have a buggy lowering that introduced [13085](https://github.com/openxla/iree/issues/13085).
[13153](https://github.com/openxla/iree/pull/13153) Removed the lowering, but it caused the failures mentioned in [13202](https://github.com/openxla/iree/issues/13202). 
Need to write a new lowering that addresses both issues.

**Comment by KoolJBlack** [comment]
Hey @NatashaKnk, @silvasean raised the point that since the removal of this lowering has caused many issues downstream, could we start with a straight `git revert` of https://github.com/openxla/iree/pull/13153 to get back to the original status quoe while you work on a further fix in the meantime? Right now we only have standins that produce terrible perf and other issued until this lowering is reintroduced.  The issue in https://github.com/openxla/iree/issues/13085 might be more constrained compared to what we have now.

**Comment by NatashaKnk** [comment]
As far as I understand, the only issue with the pass that was removed was the fact that it only performed the transposes/reshapes when the rank is >3. If that's the case, we can just re-introduce the same pass but without that limitation. I want to test it a little more but shouldn't take long. If you prefer reverting I can just write that change on top of that, or I can also just revert+write the change myself. Up to you :)

**Comment by ThomasRaoux** [comment]
We should first revert to the original state and then fix things while making sure we don't regress functional and performance.

**Comment by allieculp** [comment]
@ThomasRaoux Setting up the revert and @MaheshRavishankar reviewing. Need to discuss linalg next steps with @NatashaKnk

**Comment by ThomasRaoux** [comment]
Revert PR here: https://github.com/openxla/iree/pull/13468

**Comment by allieculp** [comment]
Revert PR looks approved. Do we have next steps for @NatashaKnk ?

**Comment by MaheshRavishankar** [comment]
Yeah, I can add some next steps and more details. Do I add these to an existing, or create a new one?

**Comment by NatashaKnk** [comment]
Closing this one as [13521](https://github.com/openxla/iree/pull/13521) was landed and we have a new issue for the next step logic.
