### ISSUE TITLE
Builtin ukernels for llvm-cpu does not generate inference output with iree-flow-enable-data-tiling

### ISSUE THREAD

**Issue by lundong** [iree-org/iree#13573]
### What happened?

When we use builtin ukernels for llvm-cpu (-iree-llvmcpu-enable-microkernels) with the iree-flow-enable-data-tiling flag, there will be run-time errors when running the target and no inference output can be generated.  The target compiled without the iree-flow-enable-data-tiling flag runs okay.

### Steps to reproduce your issue

1. Build IREE
2. Use matmul.milr at https://github.com/openxla/iree/pull/13433#issuecomment-1539078933 as an example. (Actually this issue seems to exist for any model).
3. Compile the model
/path/to/iree-compile --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-enable-microkernels --iree-flow-enable-data-tiling /path/to/matmul.mlir  -o /tmp/matmul.vmfb
4. Run the target
/path/to/iree-run-module --module=/tmp/matmul.vmfb --function=matmul_384x128x512
5. See error
main_checkout/runtime/src/iree/hal/local/executable_plugin_manager.c:568: NOT_FOUND; missing 1 required executable imports: [ukernel.mmt4d]; while invoking native function hal.executable.create; while calling import; 
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:384 /tmp/matmul.mlir:0:0; creating VM context; creating run context
6. As a comparison, if one remove the --iree-flow-enable-data-tiling flag in step 3, and repeat step 3-4, inference output will be generated.

### Version information

IREE ToT.

### Additional context

@bjacob @hcindyl

**Comment by bjacob** [comment]
The idea with the plugins that were added in #13433 is that the runtime (in your example, the `iree-run-module` program) needs to be told to load the specific plugin, which will provide the implementation of the ukernels that the testcase requires.

If you look at the testcases that were added in #13433, their CMake rules specify `RUNNER_ARGS`. These are command-line arguments passed to the test runner, which, in the case of those tests, was `iree-check-module`, but in your case here, would be `iree-run-module`.

In the case of using the system plugin (probably the easiest to use at the moment for RISC-V, since if you build it in a RISC-V build directory, it should just work):
https://github.com/bjacob/iree/blob/39e2e8ec7bad64ddcee2e05f3fa3cf697c28feb1/experimental/cpu_ukernel/test/CMakeLists.txt#L18-L19

In the case of a standalone plugin:
https://github.com/bjacob/iree/blob/39e2e8ec7bad64ddcee2e05f3fa3cf697c28feb1/experimental/cpu_ukernel/test/CMakeLists.txt#L35-L36
But at the moment, the standalone plugin only builds x86-64 and arm64 code paths, so before using it on RISC-V you would need to change that:
https://github.com/bjacob/iree/blob/39e2e8ec7bad64ddcee2e05f3fa3cf697c28feb1/experimental/cpu_ukernel/CMakeLists.txt#L76-L78

The reason why the error only manifests itself with `--iree-flow-enable-data-tiling` is that that turns `linalg.matmul`, which does not have a ukernel, into ops (`pack`, `mmt4d`, `unpack`) that do have a microkernel. So `-iree-llvmcpu-enable-microkernels` does not really have any effect at the moment without `--iree-flow-enable-data-tiling`.

In summary, your quickest route to trying out ukernels with llvm-cpu:
1. `cd` into a RISC-V build directory of IREE, e.g. `cd iree-build-riscv64`,
2. Enable building the experimental cpu ukernel plugins, `cmake . -DIREE_BUILD_EXPERIMENTAL_CPU_UKERNEL_PLUGINS=ON`
3. Build the system plugin, `cmake --build . --target iree_experimental_cpu_ukernel_builtin_ukernel_system_plugin`. This should print out the `.so` file name that was built, typically: `experimental/cpu_ukernel/builtin_ukernel_system_plugin.so` . Otherwise, `find` that file in your build dir for the next step.
4. Now run your `iree-run-module` command with this extra cmdline arg: `--executable_plugin=$(pwd)/experimental/cpu_ukernel/builtin_ukernel_system_plugin.so` ... I just added the `$(pwd)` part as I'm not sure what's each OS' policy wrt loading dynamic libraries by relative path, so an absolute path might be the most fool-proof.

**Comment by lundong** [comment]
Closing it as it is a misunderstanding, rather than a bug.
