### ISSUE TITLE
[RFC] Reference casting for vm.ref or maybe a new opaque ref type in util?

### ISSUE THREAD

**Issue by ezhulenev** [iree-org/iree#13675]
### Request description

/cc @benvanik 

I have my own container type, that in C++ looks like this:

```c++
template<typename T> // T is also a vm::RefObject
struct MyContainer : public vm::RefObject<MyContainer> {
  T get();
};
```

and a custom C++ function I want to export to IREE:

```c++
struct MyOtherType : public vm::RefObject<MyOtherType> { ... };
void Sink(vm::ref<MyOtherType>);
```

In IREE at "runtime level" I model it as a `!my.container` type (type erased), and I'd love to export a function from a custom module, that can call typed getter. How can I do this?

* **Return `vm.ref<?>` and cast it later?**

```mlir
// Import functions from my custom module
func.func private @my.container.get(!my.container) -> !vm.ref<?>
func.func private @my.sink(!my.other_type)

func.func @main(%arg0: !my.container) {
  %0 = call @my.container.get(%arg0) : (!my.container) -> !vm.ref<?>
  %1 = vm.ref_cast %0 : !vm.ref<?> to !vm.ref<!my.other_type>
  %2 = ??? : !my.other_type // how can I get an SSA value of !my.other_type from a ref
                            // or should I declare a sink function with vm types?
  call @my.sink(%2)
}
```

* **Use `util.ptr<?>`, ptr casting and ptr load?**

```mlir
// Import functions from my custom module
func.func private @my.container.get(!my.container) -> !util.ptr<?>
func.func private @my.sink(!my.other_type)

func.func @main(%arg0: !my.container) {
  %0 = call @my.container.get(%arg0) : (!my.container) -> !util.ptr<?>
  %1 = util.ptr_cast %0 : !util.ptr<?> to !util.ptr<!my.other_type>
  %2 = util.ptr.load %1 : !my.other_type
  call @my.sink(%2)
}
```

* **Introduce opaque `util.ref`?**

Given that after lowering to VM all custom types become `!vm.ref<T>` we can introduce a reference type that can be casted to any user-defined type (reference once it will get to vm level)

```mlir
// Import functions from my custom module
func.func private @my.container.get(!my.container) -> !util.ref<?>
func.func private @my.sink(!my.other_type)

func.func @main(%arg0: !my.container) {
  %0 = call @my.container.get(%arg0) : (!my.container) -> !util.ref<?>
  %1 = util.ref_cast %0 : !util.ref<?> to !my.other_type
  call @my.sink(%2)
}
```

In all these cases in the end once it's lowered to `vm` dialect it will look like this:

```
vm.func private @my.container.get(!mv.ref<!my.container>) -> !vm.ref<?>
vm.func private @my.sink(!vm.ref<!my.other_type>)

(we will need ref cast operation anyway, which at bytecode level will be noop?)
```

In theory I can import them in this form in the very beginning, but I'd love to avoid introducing `vm` types too early in the compilation pipeline, and keep all user-defined types implicitly ref-counted.

### What component(s) does this issue relate to?

Runtime

**Comment by ezhulenev** [comment]
Another idea: use type and op traits to define

1. Opaque reference type

```mlir
!my.opaque  // has trait something like Util_OpaqueRefType
```

2. Ref-casting operation inheriting Util_RefCastingOp trait

```mlir
my.ref_cast %0 : !my.opaque to !my.other_type
```

Then the example will look like this:

```
func.func private @my.container.get(!my.container) -> !my.opaque
func.func private @my.sink(!my.other_type)

func.func @main() {
  %0 = call @my.container.get(%arg0) : (!my.container) -> !my.opaque
  %1 = my.ref_cast %0 : !my.opaque to !my.other_type
  %2 = call @my.sink(%1)
}
```

Another reason why I don't want to go with `vm.ref` too early, is that I want to load `hal.buffer_view` from my container, export it as a `tensor` and pass it to compiled regions in a program (e.g. `stablehlo`)

**Comment by benvanik** [comment]
Neato! I like the idea of adding a (naming TBD) `!util.ref` type and a `util.ref.cast` op for performing the casts as a nice way to support these without needing to mutate the source dialect types. We already have a `!util.variant` that kind of does the same thing but in a special way for lists as they are the only thing that can handle both primitives (i32, f32, etc) and ref objects. This would be just a more specialized version of that which represents objects. Maybe `!util.object` is a better name as that the objects are reference counted in the VM is mostly an implementation detail (that is practically part of the contract, but still :).

One goal by using `func.func` for the externs and generic types is to be able to dump IR from a tool that may have the additional dialects compiled into to be used in tools that don't (by allowing unregistered types) and if we added interfaces or traits we wouldn't be able to handle such cases. For example, the [custom_module samples](https://github.com/openxla/iree/blob/main/samples/custom_module/basic/test/example.mlir#L13) use a `!custom.string` type that has no C++/tablegen definition anywhere but iree-compile/iree-opt can still pass it through.

As you mention we could drop the cast when lowering into the VM dialect but depending on use we could also add a VM op for it (`vm.cast.ref` etc) when narrowing the type. The advantage of having an op is that we could make type assertions much closer to where the invalid values are produced instead of at the point of consumption. For example if your container accessor returned an unexpected type the first time you'd know it was wrong would be on something that was consuming the type - if it goes in and out of globals, containers, etc in between that access and the consumer it'd be really tricky to track down. A `vm.cast.ref` doing `!vm.ref<?> -> !vm.ref<!my.type>` would fail at runtime while doing `!vm.ref<!my.type> -> !vm.ref<?>` would never fail and could be omitted from the bytecode.

Would this solve your problem?
```mlir
func.func private @my.container.get(!my.container) -> !util.object
func.func private @my.sink(!my.other_type)
func.func @main(%arg0: !my.container) {
  %0 = call @my.container.get(%arg0) : (!my.container) -> !util.object
  %1 = util.cast %0 : !util.object to !my.other_type
  call @my.sink(%2)
}
```

**Comment by ezhulenev** [comment]
Yes, ~java~.`util.object` looks to be exactly what I need!

The plan is to specialize `@my.container.get` for scalars (`.get.i32`, `get.i64`) and have a generic get for "objects".

**Comment by benvanik** [comment]
Cool - I'll see if I can get that in today!

**Comment by benvanik** [comment]
Still likely some rough edges here so please let me know if you hit any issues with this or need extra ops/support!

**Comment by ezhulenev** [comment]
Thanks, that's awesome! I'll try to lower few IR snippets that I was thinking of to see if they now can be successfully lowered to vm dialect.
