### ISSUE TITLE
Format IREE Python code with black/pyink

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#14135]
Recently, LLVM reformatted all the python code with with black: https://discourse.llvm.org/t/python-code-style-and-reformatting-status-update/70641. I also checked the Google style guide and it recommends [Black](https://github.com/psf/black) or [Pyink](https://github.com/google/pyink) for python: https://google.github.io/styleguide/pyguide.html#1-background. Switching to these would better align us with LLVM allow for less friction when graduating IREE code to LLVM.

Both are mostly configuration-less and allow comments to disable formatting of selected lines/blocks of code.

It's possible to reformat everything at once without cluttering git history using `.git-blame-ignore-revs`. This would add one more dot file to the root directory, but in exchange we can remove two existing dot files: `.pylintrc` and `.style.yapf`. We will be able to use this file for future large-scale refactorings, like the one proposed for the C++ code in: https://github.com/openxla/iree/issues/12866.

In this task, we would like to both reformat the existing python code and enforce that new and change code stays formatted through a lint check.

## Black vs. Pyink

Pyink is a fork of Black and [differs in some style choices and supported features](https://github.com/openxla/iree/issues/12866). Most notable features present in pyink but not in black are: formatting only the specified line ranges (e.g., for formatting diffs), and (optional) support for 2-space indentation. Black on the other hand seems to be more popular in the python community, and have better integrations with editors and other tools.

**Comment by kuhar** [comment]
cc: @ScottTodd, @GMNGeoffrey, @stellaraccident, @benvanik

**Comment by benvanik** [comment]
black sgtm just so we have one less tool - if we can always be in sync with what llvm is using upstream then we'll never have to worry about version drifting/disagreements

**Comment by GMNGeoffrey** [comment]
Note that although Pylint is a different tool, the only thing we have configured in there is that we use 2-space indent. So if we switch to Black and the Python-standard 4-space indent then we would be able to get rid of it. I do personally prefer the 2-space indent, but probably just because I'm used to the Google way.

One thing about formatting only modified lines is that it protects you a bit more from changes to how the formatter itself works causing a bunch of unrelated changes when someone touches a file. Similar if someone has a slightly different version locally than we enforce on CI (more lines -> more likely to hit a place they disagree). I'm not sure how big these issues will be in practice
