### ISSUE TITLE
Invalid slice of lowered model

### ISSUE THREAD

**Issue by jpienaar** [iree-org/iree#14479]
Model from https://storage.googleapis.com/chromeos-localmirror/distfiles/chromeos-audio-sr-bt-2022.09.30.tar.xz

iree-import-tflite /tmp/bt.tflite  -o /tmp/a.mlir
iree-compile  --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu --iree-input-type=tosa /tmp/a.mlir -o /tmp/a.vmfb

fails with

```
<unknown>:0: error: loc(callsite("streamable_model_11/base_conv_first/conv/strided_slice1" at "main")): 'stream.async.slice' op has invalid Read access range [1920 to 1944 for 24] of resource %0 with size 1920; end > resource size
<unknown>:0: note: loc("main"): called from
<unknown>:0: note: loc(callsite("streamable_model_11/base_conv_first/conv/strided_slice1" at "main")): see current operation: %166 = "stream.async.slice"(%162, %4, %4, %5, %8) : (!stream.resource<external>, index, index, index, index) -> !stream.resource<external>
```

**Comment by jpienaar** [comment]
(was working at 20230209.425)

**Comment by benvanik** [comment]
Reproed with iree-tools-tflite-20230524.529.

**Comment by benvanik** [comment]
I believe the issue is in the source or tflite -> tosa conversion; here's the op right after iree-import-tflite:
```mlir
%132 = "tosa.slice"(%129) <{size = array<i64: 1, 6, 1, 1>, start = array<i64: 0, 480, 0, 0>}> : (tensor<1x480x1x1xf32>) -> tensor<1x6x1x1xf32>
```

That seems to be saying "start at 0,480,0,0 of tensor 1x480x1x1 and slice out 1,6,1,1 elements" which is out of bounds. It's interesting because the adjacent ops make me think this wasn't intentional:
```mlir
    %129 = "tosa.reshape"(%arg0) <{new_shape = array<i64: 1, 480, 1, 1>}> : (tensor<1x480xf32>) -> tensor<1x480x1x1xf32>
    %130 = ml_program.global_load @"base_conv_first/conv/states" : tensor<1x6x1x1xf32>
    %131 = "tosa.concat"(%130, %129) <{axis = 1 : i64}> : (tensor<1x6x1x1xf32>, tensor<1x480x1x1xf32>) -> tensor<1x486x1x1xf32>
    %132 = "tosa.slice"(%129) <{size = array<i64: 1, 6, 1, 1>, start = array<i64: 0, 480, 0, 0>}> : (tensor<1x480x1x1xf32>) -> tensor<1x6x1x1xf32>
    ml_program.global_store @"base_conv_first/conv/states" = %132 : tensor<1x6x1x1xf32>
```

I suspect the intent was to slice out of %131 (1x486x1x1, so getting the last 6 makes sense) and not %129 (the inserted value).

Using https://netron.app I poked at the tflite file and it looks like in tflite the base_conv_first/conv/states variable is loaded, concatenated, and the result of the concatentation is then sliced out (on the left):
![image](https://github.com/openxla/iree/assets/75337/de8de655-2954-4099-8373-d441190ed79c)

So maybe this is a tflite import bug or a tosa pattern applied during import that is doing the wrong thing?

**Comment by jpienaar** [comment]
Looks like faulty Tflite to TOSA conversion, started a bisect

**Comment by jpienaar** [comment]
Seems to be between 55dd04f6bcf797b4ff20e74158377bcc912b9870 and 89a1af749166627704cdf9d676455d32616c2c06 LLVM repo side.

https://github.com/llvm/llvm-project/compare/55dd04f6bcf797b4ff20e74158377bcc912b9870...89a1af749166627704cdf9d676455d32616c2c06

**Comment by benvanik** [comment]
Going to guess https://github.com/llvm/llvm-project/commit/9e3ca7987a4dc33cdf847b79a6304b117651d21f https://reviews.llvm.org/D144545 @rsuderman

**Comment by jpienaar** [comment]
I'm going to try a local revert of it and then ping upstream.

**Comment by jpienaar** [comment]
(should be picked up by next integrate)

**Comment by jpienaar** [comment]
Works at head.
