### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 2: invalid continuation byte

### ISSUE THREAD

**Issue by lordrebel** [iree-org/iree#14695]
### What happened?

I was trying the sample `samples/colab/edge_detection.ipynb`  but got this error:
`samples/colab/edge_detection.ipynb`
I'm not downloading  iree-compiler, iree-runtime,iree-tools-tf at tag "candidate-20230426.501",instead I build the iree from source

### Version information

iree：commit 562f2ed9a3a9d12de91792dff40d64f7a180ce95 (HEAD -> main, tag: candidate-20230816.17, origin/main, origin/latest-snapshot, origin/HEAD

tf:  tf-nightly                   2.14.0.dev20230705

**Comment by ScottTodd** [comment]
Thanks for including the version information in this report! I suspect this is due to the compatibility-breaking change that landed yesterday: https://github.com/openxla/iree/commit/f022d29ad6d9c9ba793e08e529c0472a6b43af12

> This is a breaking HAL change and all existing VMFBs will fail to load on newer runtimes.

If so, you'll either need to use an older runtime (prior to that commit) or a more recent compiler (such as the next nightly, once it is built). I'm planning on pushing a stable release to pypi today, which will be from before that breaking change. Then in another week or so we may push another stable release _with_ the change.

I'm not aware of plans to increase compatibility guarantees, but we could emit some different errors or have pointers for how to get matching versions of the compiler and runtime when not building both from source.

**Comment by ScottTodd** [comment]
Hmm.. just tried this myself, and I think the `import_only=True` path is using bytecode instead of text now, hence the decode failure.

**Comment by ScottTodd** [comment]
Okay, I have a fix up for review. The `samples/colab/edge_detection.ipynb` notebook will likely need a few tweaks afterwards (to convert back from bytecode to text before printing).

**Comment by lordrebel** [comment]
I modified the code folllowing your patch, and it's works!  thx!

the sample code is here:

```python

class EdgeDetectionModule(tf.Module):

  @tf.function(input_signature=[tf.TensorSpec([1, 128, 128, 1], tf.float32)])
  def edge_detect_sobel_operator(self, image):
    # https://en.wikipedia.org/wiki/Sobel_operator
    sobel_x = tf.constant([[-1.0, 0.0, 1.0],
                           [-2.0, 0.0, 2.0],
                           [-1.0, 0.0, 1.0]],
                          dtype=tf.float32, shape=[3, 3, 1, 1])    
    sobel_y = tf.constant([[ 1.0,  2.0,  1.0],
                           [ 0.0,  0.0,  0.0],
                           [-1.0, -2.0, -1.0]],
                          dtype=tf.float32, shape=[3, 3, 1, 1])
    gx = tf.nn.conv2d(image, sobel_x, 1, "SAME")
    gy = tf.nn.conv2d(image, sobel_y, 1, "SAME")
    return tf.math.sqrt(gx * gx + gy * gy)

bytes_module = tfc.compile_module(
    EdgeDetectionModule(), import_only=True)

compiler_module = ir.Module.parse(bytes_module, ir.Context())

print("resnet50 MLIR: ", compiler_module)
edge_detection_mlir_path = os.path.join(".", "edge_detection.mlir")
with open(edge_detection_mlir_path, "w") as output_file:
  output_file.write(str(compiler_module))
print(f"Wrote MLIR to path '{edge_detection_mlir_path}'")


flatbuffer_blob = compile_str(str(compiler_module), target_backends=["vmvx"], input_type="stablehlo")
....



```

**Comment by lordrebel** [comment]
BTW， this issue may also influence the  tool : `iree-import-tf` base on the [guide](https://openxla.github.io/iree/guides/ml-frameworks/tensorflow/#using-the-command-line-tool) the `iree-import-tf` should output a mlir file that can be the input of  ` iree-compile` , but now  `iree-import-tf` output a bytecode file

**Comment by lordrebel** [comment]
> BTW， this issue may also influence the tool : `iree-import-tf` base on the [guide](https://openxla.github.io/iree/guides/ml-frameworks/tensorflow/#using-the-command-line-tool) the `iree-import-tf` should output a mlir file that can be the input of ` iree-compile` , but now `iree-import-tf` output a bytecode file

this may be caused by tensorflow , I record here:https://github.com/tensorflow/tensorflow/issues/61598

**Comment by ScottTodd** [comment]
> BTW， this issue may also influence the tool : `iree-import-tf` base on the [guide](https://openxla.github.io/iree/guides/ml-frameworks/tensorflow/#using-the-command-line-tool) the `iree-import-tf` should output a mlir file that can be the input of ` iree-compile` , but now `iree-import-tf` output a bytecode file

The tools should be able to handle (MLIR) bytecode and (MLIR) text without any extra configuration. When the bytecode format was introduced, a few tools and APIs were switched over to use it instead of text, since it is more efficient to store and transmit. However, I set those samples up to display the text form so users could follow along and see what the compiler/tools were doing and it has taken a bit of effort to switch back to using text in those places.

RE: the TensorFlow issue / method name... that has changed names a few times. My PR patches over one renaming by trying one name if the other wasn't found.
