### ISSUE TITLE
[CPU] Do not use mmt4d for non-DT on ARM

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#15750]
It looks like when DT is disabled we are falling to an old codegen path that is still using mmt4d. That is leading to some regressions and confusion since both the DT and non-DT paths use mmt4d. We should replace the non-DT mmt4d path with the non-padding matmul one.

CC: @pzread, @hanhanW, @bjacob

**Comment by hanhanW** [comment]
I think we should replace the matmul translation_info to not use mmt4d pipeline, so they can go with other matmul pipelines. If there are mmt4d ops, they still go with the mmt4d codegen pipeline.

**Comment by hanhanW** [comment]
I think the Mmt4dTilingExpert should only be used by dispatch that has [batch_]mmt4d ops. Let me create a PR that removes the old logic.

**Comment by bjacob** [comment]
Re the issue title - I would only use the terminology "use mmt4d" when there are mmt4d ops present in the IR.

Maybe the Mmt4dTilingExpert needs renaming, if it's also used for other ops.

If the Mmt4dTilingExpert really needs to be used only for mmt4d then I would like to ask if maybe it's only for historical reasons that mmt4d uses a separate expert. It seems that we should be able to codegen all linalg ops with the same set of passes, which would be free to each match on specific ops.

**Comment by hanhanW** [comment]
I am 99% sure that it's because of historical reasons. We have several generations of codegen, e.g., vectorize on memrefs, vectorize on tensors, sandbox strategy driver, etc. The ARM codegen had been paused a while because we don't have enough engineers.

We have been wanting to unify pipelines as less as possible. I've been doing deep cleanup for our CPU backends, and maybe it can be on top list. I think for the near term state, we can limit the pipeline is only used by mmt4d dispatches. Let's move other cases to our major pipeline first. I already sent out a PR for this.

Diego has been looking at mmt4d codegen, and I'm offering help as well. Once we have "clean" the mmt4d pipeline enough, it can go on the major path we've been using for codegen.

**Comment by dcaballe** [comment]
Due to the expert name I assumed we were generating mmt4d ops (but not `tensor.pack/unpack` ops), hence the title. Sorry about that.

> we can limit the pipeline is only used by mmt4d dispatches. Let's move other cases to our major pipeline first.

+1. Let's use the mmt4d only for mmt4d ops (i.e., DT without UK) and the non-pad matmul expert for non-DT.

I have changes on the fly for the pad and non-pad experts so we can think about unifying pipelines even more.

>  I'm offering help as well.

Thanks! Appreciated!
