### ISSUE TITLE
xla_hlo_before_optimizations.txt in benchmarks

### ISSUE THREAD

**Issue by jpienaar** [iree-org/iree#16057]
Why are xla_hlo_before_optimizations.txt files in the uploaded artifacts?

**Comment by pzread** [comment]
I think it's because the artifact archives are exported with https://github.com/openxla/openxla-benchmark, which we pack for different compilers. Note that we don't upload them in CI run, they are only in the downloaded model files for benchmarking. It is possible to unpack and upload them separately for IREE. 

@mariecwhite

**Comment by pzread** [comment]
Oh, I realized we only download the `stablehlo.mlirbc` from the GCS directory, then we are also not downloading the unneeded files: https://github.com/openxla/iree/blob/d6dad12a815722bff5f161352844e850f321878c/build_tools/python/e2e_test_framework/models/jax_models.py#L19

**Comment by mariecwhite** [comment]
We use the XLA dump as input to the XLA benchmark runner to run compiler-level benchmarks. It's only used in the openxla-benchmark repo, not IREE.
