### ISSUE TITLE
Missing i8 * i4 = i32, i4 * i8 = i32 ukernels

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#16156]
i8 * i4 = i32 matmuls are a critical workload in some of our models. Can we add DT+UK support for these.

**Comment by bjacob** [comment]
I'd be happy to mentor anyone wanting to do this!

First you would do the generic / non-optimized part of adding i8 x i4. You would add a i8 x i4 generic tile-function similar to this, https://github.com/openxla/iree/blob/ee9b206b75dece2e7025b0d237ff6176ea927cae/runtime/src/iree/builtins/ukernel/mmt4d_tile.c#L79-L120 , you would add the corresponding logic to select that tile function similar to this, https://github.com/openxla/iree/blob/ee9b206b75dece2e7025b0d237ff6176ea927cae/runtime/src/iree/builtins/ukernel/mmt4d_tile.c#L423-L424 , and you would extend `mmt4d_test.c` to cover it similar to https://github.com/openxla/iree/blob/ee9b206b75dece2e7025b0d237ff6176ea927cae/runtime/src/iree/builtins/ukernel/tools/mmt4d_test.c#L502, adding test reference code similar to https://github.com/openxla/iree/blob/ee9b206b75dece2e7025b0d237ff6176ea927cae/runtime/src/iree/builtins/ukernel/tools/mmt4d_test.c#L184-L203 .

Then you would start the optimized-code part of this, for any target architecture that you care about. If you are looking at x86-64, you could start by studying the i16 x i4 ukernel, https://github.com/openxla/iree/blob/ee9b206b75dece2e7025b0d237ff6176ea927cae/runtime/src/iree/builtins/ukernel/arch/x86_64/mmt4d_x86_64_avx512_vnni.c#L258-L364 . Since it works by splitting the i16 side into high and low 8bit halves, your i8 x i4 case would be essentially half of that kernel.  You would then add a corresponding case to `mmt4d_benchmark.c` to get a microbenchmark for this.

**Comment by mariecwhite** [comment]
Thanks Benoit, I can work on this one.

**Comment by bjacob** [comment]
Great! Note, if your main target architecture is arm64, good starting points are the existing `s8s8s32` kernels there, for +i8mm (if targeting Pixel8 or Qualcomm Snapdragon 8 gen 1 or newer devices) or +dotprod (if targeting older devices or Apple devices --- note that while recent Apple CPUs support +i8mm, they perform poorly on it, at least my Apple M2 does).

https://github.com/openxla/iree/blob/ee9b206b75dece2e7025b0d237ff6176ea927cae/runtime/src/iree/builtins/ukernel/arch/arm_64/mmt4d_arm_64_i8mm.c#L30-L97
