### ISSUE TITLE
Transform preprocessing spec is unusably slow on real-world inputs

### ISSUE THREAD

**Issue by kuhar** [iree-org/iree#16901]
Simplest transform spec to illustrate the issue:
```mlir
// spec.mlir
module attributes { transform.with_named_sequence } {
  transform.named_sequence @match_generic(%entry: !transform.any_op {transform.readonly}) -> !transform.any_op {
    transform.match.operation_name %entry ["linalg.generic"] : !transform.any_op
    transform.yield %entry : !transform.any_op
  }

  transform.named_sequence @__transform_main(%variant_op: !transform.any_op {transform.consumed}) {
    %generic = transform.collect_matching @match_generic in %variant_op
      : (!transform.any_op) -> !transform.any_op

    transform.print %generic {name = "Generic"} : !transform.any_op
    // Transform the matched generic.
    transform.yield
  }

  transform.named_sequence @__preprocessing_main(%variant_op: !transform.any_op {transform.readonly}) {
    transform.yield
  }
} //  module
```

Repro:

```shell
wget https://sharkpublic.blob.core.windows.net/sharkpublic/ian/stable_diffusion_xl_base_1_0_64_1024x1024_fp16_unet_linalg_nithin.mlir

tools/iree-compile --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx942 stable_diffusion_xl_base_1_0_64_1024x1024_fp16_unet_linalg_nithin.mlir --iree-preprocessing-transform-spec-filename=spec.mlir
```

This input mlir has <50 kLOC and contains 8583 `linalg.generic` ops. With the transform script above, I can only match ~560 `linag.generic`s in 30 seconds. This doesn't make it a viable solution for real-world inputs.

Are there some knobs I could tweak to make it go faster? Alternatively, maybe we could do some pre-filtering at the level of C++, e.g., wrap the transform dialect interpreter in a pass pipeline (that could be specified as a CLI pipeline string).

cc: @Groverkss @harsh-nod @ftynse @matthias-springer @maerhart

**Comment by matthias-springer** [comment]
Two things that come to mind: Make sure to build in `Release` mode and make sure that `enable-expensive-checks=0`. (I think that's the default.)

If that doesn't improve the situation, I'd generate a flame graph to see where we spend the most time. I think we haven't looked much at performance so far.

**Comment by kuhar** [comment]
Thanks @matthias-springer, I will try to drill into this a bit more tomorrow.

> Two things that come to mind: Make sure to build in Release mode and make sure that enable-expensive-checks=0. (I think that's the default.)

I'm using a release with assertions build. I don't know about the expensive checks, I didn't enable anything in cmake like `LLVM_ENABLE_EXPENSIVE_CHECKS` -- is there another knob to control this for transform scripts?
Separately, I'd argue that even if this was a debug build, any checks that cause such slowness are probably 'too expensive'.

**Comment by matthias-springer** [comment]
There's another knob and looks like it's enabled in IREE by default:
In `compiler/src/iree/compiler/Codegen/Common/TransformDialectInterpreterPass.cpp`:
```
    if (failed(transform::applyTransformNamedSequence(
            payloadRoot, transformEntryPoint, transformModule,
            options.enableExpensiveChecks(true))))
      return signalPassFailure();
```

I would keep these checks enabled in most tests and deactivate them only on integration tests and benchmarks. They could save you a lot of debugging.

**Comment by matthias-springer** [comment]
That being said, I would be surprised if deactivating expensive checks improved performance much in this example. The expensive checks look for usage of invalidated handles etc., and there are not many handles in this example. So we should probably still run with a profiler. I think there are quite a few checks (like checking that the type of payload ops matches the handle type in the IR; that's probably not the cause of the slowdown here) that could be skipped in optimized mode.

**Comment by ftynse** [comment]
Is there any possibility to reproduce this with upstream mlir only?

**Comment by kuhar** [comment]
> There's another knob and looks like it's enabled in IREE by default: In `compiler/src/iree/compiler/Codegen/Common/TransformDialectInterpreterPass.cpp`:
> 
> ```
>     if (failed(transform::applyTransformNamedSequence(
>             payloadRoot, transformEntryPoint, transformModule,
>             options.enableExpensiveChecks(true))))
>       return signalPassFailure();
> ```
> 
> I would keep these checks enabled in most tests and deactivate them only on integration tests and benchmarks. They could save you a lot of debugging.

With expensive checks disabled it **doesn't** get noticeably faster.

I captured a flame graph:
![image](https://github.com/openxla/iree/assets/4612584/e7772dea-7ed3-4e72-9c5c-78376b597c11)

**Comment by benvanik** [comment]
I'm going to guess it's your print op - printing requires verification and calculating asm state for the entire parent context (which is your big enclosing scope) in order to get the SSA value names.

(it looks like linalg verification is extremely slow - which we've seen before and it'd be really good to improve - we can't be telling users to disable verification and yolo through just to make linalg fast enough to use)

**Comment by kuhar** [comment]
Printing is just a part of the minimum repro. When I tried doing the actual match and transform the matching ops it was also extremely slow.

**Comment by benvanik** [comment]
gotcha - you'll want to capture without the print then, as it's likely skewing things too far to see what the actual cause is

**Comment by kuhar** [comment]
Here is a minimized version of the preprocessing I had in mind:
![image](https://github.com/openxla/iree/assets/4612584/e68f810c-89f5-46e2-ba8e-4cc5ab74801a)

Transform script:
```mlir
module attributes { transform.with_named_sequence } {
  transform.named_sequence @match_generic(%entry: !transform.any_op {transform.readonly}) -> !transform.any_op {
    transform.match.operation_name %entry ["linalg.generic"] : !transform.any_op
    transform.yield %entry : !transform.any_op
  }

  transform.named_sequence @match_mmt_f16_f16_f32(%root: !transform.any_op {transform.readonly}) -> (!transform.any_op) {
    transform.match.operation_name %root ["linalg.generic"] : !transform.any_op
    %ins, %outs = transform.iree.match.cast_compatible_dag_from_root %root {
      ^bb0(%lhs: tensor<?x?xf16>, %rhs: tensor<?x?xf16>, %out: tensor<?x?xf32>):
      %7 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d2)>,
                                            affine_map<(d0, d1, d2) -> (d1, d2)>,
                                            affine_map<(d0, d1, d2) -> (d0, d1)>],
                           iterator_types = ["parallel", "parallel", "reduction"]}
          ins(%lhs, %rhs : tensor<?x?xf16>, tensor<?x?xf16>) outs(%out : tensor<?x?xf32>) {
        ^bb0(%in: f16, %in_0: f16, %acc: f32):
          %8 = arith.extf %in : f16 to f32
          %9 = arith.extf %in_0 : f16 to f32
          %10 = arith.mulf %8, %9 : f32
          %11 = arith.addf %acc, %10 : f32
          linalg.yield %11 : f32
        } -> tensor<?x?xf32>
    } : (!transform.any_op) -> (!transform.any_value, !transform.any_value)
    transform.yield %root : !transform.any_op
  }

  transform.named_sequence @apply_splitk_config(%op: !transform.any_op {transform.readonly},
                                                %config: !transform.any_param {transform.readonly}) {
    transform.annotate %op "iree_flow_split_reduction_ratio" = %config : !transform.any_op, !transform.any_param
    transform.print %op {name = "Applied"} : !transform.any_op
    transform.yield
  }

  transform.named_sequence @match_mmt_2048x1280x5120(%matmul: !transform.any_op {transform.readonly})
    -> (!transform.any_op, !transform.any_param) {
    %mmt = transform.include @match_mmt_f16_f16_f32 failures(propagate) (%matmul) : (!transform.any_op) -> !transform.any_op
    %lhs = transform.get_operand %matmul[0] : (!transform.any_op) -> !transform.any_value
    %rhs = transform.get_operand %matmul[1] : (!transform.any_op) -> !transform.any_value
    transform.iree.match.cast_compatible_type %lhs = tensor<2048x5120xf16> : !transform.any_value
    transform.iree.match.cast_compatible_type %lhs = tensor<1280x5120xf16> : !transform.any_value
    %config = transform.param.constant 4 -> !transform.any_param
    transform.yield %matmul, %config : !transform.any_op, !transform.any_param
  }

  transform.named_sequence @__transform_main(%variant_op: !transform.any_op {transform.consumed}) {
    transform.foreach_match in %variant_op
      @match_mmt_2048x1280x5120 -> @apply_splitk_config
     : (!transform.any_op) -> (!transform.any_op)
    transform.yield
  }

  transform.named_sequence @__preprocessing_main(%variant_op: !transform.any_op {transform.readonly}) {
    transform.yield
  }
} //  module
```

Most of the time is spent in verification logic. I made sure to disable expensive checks in the interpreter pass.

**Comment by kuhar** [comment]
This is actually interesting because the `Operation::print` is there even when I comment out any prints in the TD spec, it comes from the match diagnostics.

**Comment by benvanik** [comment]
This is:
```c++
    // Verify general operation equality (name, attributes).
    DiagnosedSilenceableFailure diag =
        compareCastCompatibleOperations(*this, targetOp, payloadOp);
    if (!diag.succeeded()) {
      diag.attachNote() << "While processing operation " << *payloadOp;
      return diag;
    }
```

in `MatchCastCompatibleDagFromRootOp::matchOperation`.
the failure there is used as control flow - the caller is just like "cool, you didn't match, discard whatever diagnostics you produced and continue trying to match stuff" - only attachNote() is causing the entire program to be printed to attach the note that is then discarded.

Try removing that attachNote.

I don't know what DiagnosedSilenceableFailure is, but many times the InFlightDiagnostics will let you provide a callback that is captured and then issued only when the message needs to be generated so if the failure is ignored/used for control flow the only overhead was capturing the std::function. It should definitely be doing that if this is an expected use case.

**Comment by kuhar** [comment]
For just the matching, https://github.com/openxla/iree/pull/16914 makes the performance reasonable for me.

How could we improve it for printing? I guess we would have to avoid op verification. Maybe add an attribute to print using the generic syntax and skip verification? (Just guessing, it got late and I haven't checked the exact call path with printing only.)

**Comment by ftynse** [comment]
> Maybe add an attribute to print using the generic syntax and skip verification? (Just guessing, it got late and I haven't checked the exact call path with printing only.)

We can add all of the printing flags as attributes, these flags include "assume verified" that will bypass verification (but crash on invalid IR) and "print generic format. You are welcome to tag me on the upstream patch.

**Comment by benvanik** [comment]
The best thing to do is to not print unless the user asks for it - here, attachNote should take an std::function (or function_ref, whatever) that is called only if the diagnostic is presented to the user. See the pattern rewriter notifyMatchFailure that does the same: it takes a callback that is only invoked if the failure message is emitted (during debug prints or error messages) allowing all patterns to include useful failure messages without incurring the cost of printing at each step. May require some upstream refactoring to make that happen, but it's the best solution if printing the operation (and not just its name) is needed as part of normal execution.

Assume-verified is potentially useful but also potentially very dangerous and we want to be extremely cautious of using it: if this is running during transform execution and the reason a match fails is because the immediately preceding transform did something invalid then printing the error message could cause a crash. When we've had that issue before it's made triage really hard as the crashing stack will end up in something totally unrelated to where the change was made. Verification being slow **once** in order to print out an error message isn't bad (well, not good, either :) and we should be working towards that.

Verification is also just the worst thing here, but the AsmState construction from the surrounding isolated-from-above context is also expensive and we don't want that happening during normal execution. For that we really need the proper fix of not printing unless the error is being emitted. The other optimization there is amortizing the cost if there are multiple errors printed because we know there's no modifications happening during error printing and can pass the same AsmState to every printer. notifyMatchFailure could take an optional `AsmState&` and our debug printing during pattern matching would be much faster, for example.

**Comment by kuhar** [comment]
I opened a PR with some op printing flags: https://github.com/llvm/llvm-project/pull/86846

Using `assume_verified` and `use_local_scope` makes the performance reasonable for me.

**Comment by stellaraccident** [comment]
I believe that @benvanik is correct and offers good advice.

**Comment by kuhar** [comment]
@benvanik and @stellaraccident I think something might be lost in translation here, this got a bit confusing because we ran into two separate but similar issues:

1. An IREE transform op that unnecessarily printed ops that failed to match to the diagnostic. The fix was local: I changed it to only print the op location in  https://github.com/openxla/iree/pull/16914 .
2. Printing matched ops with `transform.print` is slow because it entails verification and printing of regions. These ops are basically user-printf debug ops only introduced by hand AFAIK.  I have a proposed PR that allows users to make printing cheaper by setting *local* op print flags and skip verification/regions: https://github.com/llvm/llvm-project/pull/86846. This is not a new default and does not seem unsafe/risky -- I expect that these flags will be rarely used when the user wants to debug their transform script and realizes that they need to print a large number of ops.

IIUC, what Ben said assumes transform op unconditionally print match failures to diagnostics, but I don't think this is the case in general. That one instance seemed like an isolated bug on the IREE side. I don't have much experience with the transform dialect so I could be missing some pattern here, but for me fixing 1. and 2. made the performance reasonable on the SDXL bytecode.

**Comment by benvanik** [comment]
IMO, transform.print is a user-level action and should never cause a compiler crash. Disabling verification can lead to compiler crashes. Thus, I'd not disable verification for that op by default. The cases for disabling verification would be if you ran verification successfully and then printed without any intervening changes - such as an analysis pass that didn't mutate IR. You can't guarantee this with transform dialect, though, AFAIK: your one transform can have a transform.print but another that ran earlier in the same context could have mutated the IR into a state where verification would fail, even if you had verified prior to entering the transform scope. You could potentially set a mutation bit (and transform dialect's executor may already have this) and if there was a successful verification then avoid verification for prints but it is unsafe to do so otherwise. Whether you want to take that risk or not is orthogonal to whether a user-level action should by default (and without needing to change/modify the compiler) force that risk onto users. I often run with -verify=false to speed things up when iterating on large models where I know it won't matter (or the bots will catch a failure if I forget) but I wouldn't disabling verification by default for performance reasons.

A global flag that disabled verification on printing feels much more appropriate for the risk (and it may already exist) - if _you_ for _your_ input and _your_ mix of transforms running at the exact point _you_ run them find it safe then it's cool to set such a flag (and maybe you always set it) - but if transform dialect is used in several places (as it is in IREE) on both untrusted and trusted inputs (IR near the head of the pipeline, IR modified by any number of loaded transform scripts, etc) it's not a good default.

**Comment by benvanik** [comment]
Ah I didn't see that you made them non-default options in your PR - then yeah, who cares #yolo :P
(my only concern is defaults that lead to users hitting errors that then we have to triage/debug - if a user opts into something that crashes that's on them - like when I set -verify=false I'd expect someone to tell me to not do that if I filed a bug about a crash :)

**Comment by ftynse** [comment]
> The best thing to do is to not print unless the user asks for it - here, attachNote should take an std::function (or function_ref, whatever) that is called only if the diagnostic is presented to the user. See the pattern rewriter notifyMatchFailure that does the same: it takes a callback that is only invoked if the failure message is emitted (during debug prints or error messages) allowing all patterns to include useful failure messages without incurring the cost of printing at each step. 

This is a good observation, but there is a caveat. The objects references to which are captured by the callback must remain live until the callback is called, which is not immediate for silenceable failures (and also the reason why one must not use `function_ref` for this case). This is not guaranteed for IR objects such as operations. Debugging _that_ is particularly painful and often escapes asan-style tooling due to how the allocator reuses addresses..

In both cases, it boils down to trusting the author of particular transform ops to write diagnostics "carefully", i.e., not print entire ops unnecessarily or not capture them when the diagnostic may outlive the op.

> You can't guarantee this with transform dialect, though, AFAIK: your one transform can have a transform.print but another that ran earlier in the same context could have mutated the IR into a state where verification would fail, even if you had verified prior to entering the transform scope. 

The general contract is that transformations must return a definite failure if they rendered IR invalid. Definite failures are immediately propagated up until exiting the transform infra altogether. More explicit validity annotations can be considered as region-carrying transform ops if desired.
