### ISSUE TITLE
Merge `round_dims_to` and `matmul_narrow_{M,N}` into a single `max_padding` array attribute

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#17729]
This is a take 2 on https://github.com/iree-org/iree/issues/17553. There, I had suggested renaming `round_dims_to` to `max_padding` and making it a scalar, while retaining `matmul_narrow_{M,N}` overriding it for narrow dimensions and clarifying the whole semantics.

Last week we discussed in-person that it would be even nicer to resolve this the other way around: keep the renaming of `round_dims_to` to `max_padding` but keep that an array attribute and instead drop the separate `matmul_narrow_{M,N}`, folding their semantics into that.

**Comment by lialan** [comment]
@bjacob given that `matmul_narrow_{M,N}` are optional attributes, wouldn't it be better to make `max_paddings` to be a dictionary attribute?

**Comment by lialan** [comment]
As per discussion with @bjacob , we will pause this issue. Reasons being:
1. padding is being removed so querying narrow dimensions can be made by querying source tensor types. Related PR here: https://github.com/iree-org/iree/pull/17931
2. prioritize #17922 instead of this.


Note: The implementation related to this PR is: https://github.com/iree-org/iree/pull/17898 . Possible subsequent updates to this  PR: can remove `matmul_narrow_M`, `matmul_narrow_N`, `original_type`, and `iree_encoding.upper_bound_tile_size`
