### ISSUE TITLE
Does the front-end support onnx-mlir? Why not use Onnx-mlir directly when importing onnx, but use Torch-mlir to convert the onnx file into the torch dialect?

### ISSUE THREAD

**Issue by hphyhl** [iree-org/iree#18788]
![Image](https://github.com/user-attachments/assets/256af489-6fa8-4065-a710-b1965a18ec6e)

**Comment by stellaraccident** [comment]
No it does not. Frontends are expensive and we preferred to leverage the joint work to make both take the same path and exercise the same pipelines in order to have them both be first class and get the benefit of testing. We've found that doubling up investment on the same path through is more efficient than having a lot of independent multi-hop partial conversions at this layer. In some cases, it pushes us to make the torch support more robust, but pretty much every modern onnx model is coming from torch anyway, so there is a lot of overlap.
