### ISSUE TITLE
[runtime] Support npy format when tensor tracing

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree#18962]
### Request description

The high-level goal is to have a more concise representation when we have to dump a lot of large tensors. Also interoperability with other software like NumPy and PyTorch is good.

Currently tensor tracing with [iree_hal_modules_buffer_view_trace](https://github.com/iree-org/iree/blob/2ec9017bb1de7d5ba552c1f016326088864b9cf9/runtime/src/iree/modules/hal/utils/buffer_diagnostics.c#L253) formats its output for human readability. E.g.
```
EXEC @main
=== my_tensor ===
2xf32=1 2
```
I would like to be able to dump in npy format. We already support in `iree-run-module` this format as input/output.
An alternative is to use the irpa format.

It is desirable also to allow sinking the output into a file(s) and not to stderr.

Maybe we could control this through environment variables and/or add flags to the various tools.

### What component(s) does this issue relate to?

Runtime

**Comment by sogartar** [comment]
I am willing to implement this.

**Comment by benvanik** [comment]
You've hit the limit in printf debugging if you want something more than textual. Dumping every tensor input/output as the automatic stuff for printf debugging provides for quick isolated sanity checks but does not scale to large values or large numbers of values.

npy is not a good format and not something we want in the core runtime - it doesn't support a fraction of the data types we do and is a poor format for large volumes of data (no index, file size limits, etc).

If you are in the python level you can add a python custom module and route buffer views to that for data sciencey things - then you could dump to numpy if you wanted (or any other format). You can insert the calls to your custom module at whatever points semantically make sense (instead of every tensor everywhere duplicated all of the time) and correlate them with whatever custom tracking you want (stable identifiers, etc).

IOW: iree_hal_modules_buffer_view_trace is strictly for printf debugging, and anything beyond printf debugging needs something else. Custom modules let you do whatever you want tailored to your scenario and can have limited support for just what you need vs. something in core that needs to support everything.

**Comment by benvanik** [comment]
(it'd be useful to pull back from this specific implementation and discuss what you are actually trying to do - there are many ways to do things)

**Comment by benvanik** [comment]
#18966 allows for injecting a different trace sink - if you are programmatically creating your HAL module you can provide your own. If we did want to write other formats we can now do it without infecting the core implementation. npy is still a bad format though - if we can find one that supports arbitrary data types or want to generate IRPA files (as they support append mode) we could do that now entirely in tooling/.

**Comment by sogartar** [comment]
@benvanik, thank you for the suggestions. I want to trace some tensors in IREE-Turbine eager execution and when running an IREE module.
I was thinking of using `flow.tensor.trace` for that. I will explore you suggestion, it looks like exactly what I want.

**Comment by benvanik** [comment]
If you are inserting the traces yourself (instead of the automatic insertion) then you will have a better time - the default "trace everything" is not good (it'll trace duplicates, entire tensors regardless of how much a particular dispatch touches, etc) - if you have for example a 32GB kvcache it'll trace all 32GB as the input and result of everything touching it even if you're only inserting a 1KB value, etc.

#18966 makes it possible for you to hack some code in a branch to try things - you can also do it all the way in python with some plumbing to pass a function into the `hal.create_hal_module` API. Spend some time experimenting and seeing if it works for you and then we can maybe figure out what kind of support we want in the default iree-run-module tooling.

**Comment by sogartar** [comment]
@benvanik's callback approach is flexible and allows for users to do what they want. If we really need more custom tracers available in IREE I will reopen this. For example if we need to set them when using `iree-run-module`.
