### ISSUE TITLE
pkg_ci failure: test_sdxl_rocm_benchmark

### ISSUE THREAD

**Issue by amd-chrissosa** [iree-org/iree#19442]
### What happened?

From: https://github.com/iree-org/iree/actions/runs/12263343955/job/34215271973
	FAILURE: check 80.4 <= 80.0: SDXL unet benchmark time should not regress
	FAILURE: check 57.9 <= 53.0: SDXL punet f8 benchmark time should not regress

### Steps to reproduce your issue

Commit a CL to iree-org

**Comment by amd-chrissosa** [comment]
Following up with @nithinsubbiah this is intentional - see commit msg here: https://github.com/iree-org/iree/commit/7177c29f9b2d9e255b63987f5dfff174ec2afc2f

Will be addressed when CL is relanded.

**Comment by nithinsubbiah** [comment]
@amd-chrissosa If you meant if the regression was intentional, no. We had to revert that commit to get our perf back up. I hope that clears things up

**Comment by amd-chrissosa** [comment]
Ah, then this regression is unintentional - so we reverted a CL to get perf back up but simultaneously reverted performance on unet and punet @saienduri  for thoughts.

**Comment by saienduri** [comment]
Posted on the discord, but there isn't actually a regression here. The revert passed presubmit (https://github.com/iree-org/iree/actions/runs/12262757805/job/34213290843) and failed benchmarking threshold on the postsubmit (gave it a re-run and passed). This does happen once in a while. We have been trying to find the sweet spot over the last couple of months on the thresholds (catching regressions, but not too many false negatives). Numbers vary based on gpu/traffic, so it's unfortunately a price we have to pay for no significant regressions on halo models. And regarding changing a test, most compiler folks are aware that this is the place to do so https://github.com/iree-org/iree/blob/7177c29f9b2d9e255b63987f5dfff174ec2afc2f/.github/workflows/pkgci_regression_test.yml#L241, so that's been easy enough to keep updated as a team

**Comment by amd-chrissosa** [comment]
Timeouts adjusted here: https://github.com/nithinsubbiah/iree/commit/59e96e0a32f58e652870cde9926d1ed2591e9c0e . Closing for now.

**Comment by ScottTodd** [comment]
> Timeouts adjusted here: [nithinsubbiah@59e96e0](https://github.com/nithinsubbiah/iree/commit/59e96e0a32f58e652870cde9926d1ed2591e9c0e) . Closing for now.

That commit is in a fork. Did you mean https://github.com/iree-org/iree/commit/e9e8b9fd8755cdae3923e3515b0d6ce3e67c674c ?

**Comment by amd-chrissosa** [comment]
Thanks yes I missed that that was a fork from the discord discussion.
