### ISSUE TITLE
Figure out type conversion issues in std->vm conversion

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#2878]
If the VMLA type converter is provided to the ConstantOpConversion when inserted:
```
patterns.insert<ConstantOpConversion>(typeConverter, context);
```

MLIR's behavior changes and things get broken:
```
D:\Dev\iree/iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir split at line #83:8:12: error: failed to materialize conversion for result #0 of operation 'std.constant' that remained live after conversion
      %0 = "mhlo.reduce"(%arg0, %cst) ( {
```

Removing the TypeConverter makes things work. No clue why.

Repro:
1. Add the typeConverter arg to the patterns.insert at the bottom of ConvertStandardToVM.cpp 
2.
```
iree-opt -debug -mlir-disable-threading -print-ir-after-all -iree-transformation-pipeline -iree-hal-target-backends=vmla iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir
```

**Comment by River707** [comment]
> If the VMLA type converter is provided to the ConstantOpConversion when inserted:
> 
> ```
> patterns.insert<ConstantOpConversion>(typeConverter, context);
> ```
> 
> MLIR's behavior changes and things get broken:
> 
> ```
> D:\Dev\iree/iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir split at line #83:8:12: error: failed to materialize conversion for result #0 of operation 'std.constant' that remained live after conversion
>       %0 = "mhlo.reduce"(%arg0, %cst) ( {
> ```
> 
> Removing the TypeConverter makes things work. No clue why.

The switch to make dialect conversion type-safe is only half way done. If you don't provide a type converter, it defaults to ignoring type safety to preserve those currently dependent on the old behavior. I'll try to break down exactly what is happening for this particular situation:

To start off with, let's look at the error that is being generated:
```
iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir:90:12: error: failed to materialize conversion for result #0 of operation 'std.constant' that remained live after conversion
      %0 = "mhlo.reduce"(%arg0, %cst) ( {
           ^
iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir:88:5: note: called from
    func @reduction_ex_dispatch_0(%arg0: tensor<4x8xf32>) -> tensor<4xf32> {
    ^
iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir:90:12: note: see current operation: %c4_8 = "std.constant"() {value = 4 : index} : () -> index
      %0 = "mhlo.reduce"(%arg0, %cst) ( {
           ^
iree/compiler/Dialect/HAL/Target/VMLA/test/smoketest.mlir:90:12: note: see existing live user here: vm.call.variadic @vmla.reduce.sum.f32(%ref_6, [%c4_8, %c8_9], %ref, [], %c1_i32, %ref_7, [%c4_11]) : (!vm.ref<!vmla.buffer>, i32 ..., !vm.ref<!vmla.buffer>, i32 ..., i32, !vm.ref<!vmla.buffer>, i32 ...)
```

Here it is complaining that the conversion framework could not materialize a conversion for result #0 of a std.constant that remained live after conversion. This means that the std.constant was replaced by a value of a different type, but the original value still has users that will be live(i.e. not replaced/erased) after the conversion finishes. The particular user that remains live is `vm.call.variadic @vmla.reduce.sum.f32`.
(I really need to make that error message much longer, pretty bad right now)

* The live `vm.call.variadic` is generated during VMLA -> VM when it converts the following operation that was produced at some point when `mhlo.reduce` was lowered:
```
"vmla.reduce.sum"(%3, %rs4_8, %1, %rs, %4, %rs4) {dimension = 1 : i32, element_type = f32} : (!vmla.buffer, !shapex.ranked_shape<[4,8]>, !vmla.buffer, !shapex.ranked_shape<[]>, !vmla.buffer, !shapex.ranked_shape<[4]>) -> ()
```

We can confirm this by looking for our vm.call.variadic in the debug output:

```
//===-------------------------------------------===//
Legalizing operation : 'vmla.reduce.sum'(0x4b879e0) {
  "vmla.reduce.sum"(%3, %rs4_8, %1, %rs, %4, %rs4) {dimension = 1 : i32, element_type = f32} : (!vmla.buffer, !shapex.ranked_shape<[4,8]>, !vmla.buffer, !shapex.ranked_shape<[]>, !vmla.buffer, !shapex.ranked_shape<[4]>) -> ()

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'vmla.reduce.sum -> ()' {
    ** Insert  : 'std.constant'(0x4b5c540)
    ** Insert  : 'std.constant'(0x4b6a8d0)
    ** Insert  : 'std.constant'(0x4b96d20)
    ** Insert  : 'std.constant'(0x4b96dd0)
    ** Insert  : 'vm.call.variadic'(0x4b86570)
    ** Replace : 'vmla.reduce.sum'(0x4b879e0)
```

We also see some std.constants here, which is a pretty good indicator that the problem is originating here. The lowering for `vmla.reduce.sum` is implemented with `rewriteToCall`(in ImportUtils.h), which lowers to our `vm.call.variadic`. This lowering has special logic when the original operands of the operation being converted are of shapex.ranked_shape, which is the case here.

```
        // Expand a ranked_shape into its dimensions.
        // We need to rematerialize the static dimensions and then pass through
        // the new dynamic dimensions that we have the SSA values for.
        auto rankedShapeType = oldOperands[0]
                                   .getType()
                                   .template dyn_cast<Shape::RankedShapeType>();
        for (int i = 0; i < rankedShapeType.getRank(); ++i) {
          auto dimOp = rewriter.createOrFold<Shape::RankedDimOp>(
              op.getLoc(), oldOperands[0], i);
          state.addOperands(dimOp);
        }
```

The `std.constant` operations from above are generated with a result type of `index` when folding this `Shape::RankedDimOp`. These `index` constants are then fed to `vm.call.variadic` when it gets generated. Our generated `vm.call.variadic` is then marked as `legal` for the conversion target while still having the `index` operands:

```
    //===-------------------------------------------===//
    Legalizing operation : 'vm.call.variadic'(0x4b86570) {
      "vm.call.variadic"(%ref_6, %c4_8, %c8_9, %ref, %c1_i32, %ref_7, %c4_11) {callee = @vmla.reduce.sum.f32, segment_sizes = dense<[-1, 2, -1, 0, -1, -1, 1]> : vector<7xi16>, segment_types = [!vm.ref<!vmla.buffer>, i32, !vm.ref<!vmla.buffer>, i32, i32, !vm.ref<!vmla.buffer>, i32]} : (!vm.ref<!vmla.buffer>, index, index, !vm.ref<!vmla.buffer>, i32, !vm.ref<!vmla.buffer>, index) -> ()

    } -> SUCCESS : operation marked legal by the target
    //===-------------------------------------------===//
```

Herein lies the problem. From the perspective of the conversion framework, the use of a value and its definition establish a "type contract" that is not allowed to be broken. If an operation consumes a specific type, in this case `index`, the type being consumed will not implicitly change, even if the producer type changes. In such cases where the producer type changes, the framework will materialize a conversion from the new producer type to the old consumed type. You might say "wait a minute, I made sure to legalize the `index` to the proper type afterwards", which is true. If we look at the output, the `index` constants are properly legalized:

```
    //===-------------------------------------------===//
    Legalizing operation : 'std.constant'(0x4b5c540) {
      %c4 = "std.constant"() {value = 4 : index} : () -> index

      * Fold {
      } -> FAILURE : unable to fold

      * Pattern : 'std.constant -> ()' {
        ** Insert  : 'vm.const.i32'(0x4b96e90)
        ** Replace : 'std.constant'(0x4b5c540)

        //===-------------------------------------------===//
        Legalizing operation : 'vm.const.i32'(0x4b96e90) {
          %c4 = "vm.const.i32"() {value = 4 : i32} : () -> i32

        } -> SUCCESS : operation marked legal by the target
        //===-------------------------------------------===//
      } -> SUCCESS : pattern applied successfully
    } -> SUCCESS
    //===-------------------------------------------===//
```

The problem is that by this point a type contract has already been established between the old `std.constant` and the `vm.call.variadic`. This means that even though the std.constant was legalized to something producing the type you expected, `i32`, but the `vm.call.variadic` is already expecting to consume an `index`. Now at this point the question is probably "well that sucks, what am I supposed to do about that?". There are a couple options that still preserve the nature of "type contract", but help prevent annoyances such as this:

*) Don't create and consume a known illegal type
The easiest option is to not create and consume an illegal type in the first place. In this situation, you already know that a value of `index` is never going to be valid. The handling of `ranked_shape` could be modified to make sure the constant is a valid type.

*) Add a passthrough type conversion-esque pattern
If you don't know that you are generating something illegal inside of the pattern itself, the common thing is to have a type conversion pattern for the operations that are effectively 1-1. This is like the [CallOpTypeConversion](https://github.com/llvm/llvm-project/blob/48cd5b72b13c1283eedb0f3fac7c14167da7fc2f/mlir/lib/Dialect/StandardOps/Transforms/FuncConversions.cpp#L18) pattern in the standard dialect.

*) Have some mechanism to know if an operation can just accept the new type
This one is a bit tricky, because in the context of conversions it can get really weird to assume things. One thing the conversion infra "might" be able to do is just know that "Hey, this op was created in a pattern with this TypeConverter, so I'm just going to assume that I can update the type of the operand because the TypeConverter says the new type is legal". This feels a little dirty, because one could technically intend to create something with an illegal operand(not sure why). 

Open to other suggestions as well.

**Comment by benvanik** [comment]
VMLA is dead. We may still have issues but I don't think we can track it from this.
