### ISSUE TITLE
How to create a standalone executable?

### ISSUE THREAD

**Issue by monkbai** [iree-org/iree#4609]
Can IREE convert a model into a standalone executable file that can run independently?

**Comment by stellaraccident** [comment]
The lab that @marbre works at has been working on the "emit-c" support that has things in this direction as one of its goals. Marius, I know you had some progress but I'm not up to date on the overall status.

**Comment by benvanik** [comment]
It also depends on what you want to do -- are you literally asking if it's possible to produce an executable so you could do something like `./my-model inputs.txt > outputs.txt`? If so, that is something you could do today by using IREE as a component of your own executable - it's how we do a lot of our testing, for example. The `iree/samples/simple_embedding` sample shows this off by embedding the IREE compiler output into a header file:
https://github.com/google/iree/blob/main/iree/samples/simple_embedding/simple_embedding_test.cc#L31

You can follow guides like this for how best to embed binary files in your executables: https://codeplea.com/embedding-files-in-c-programs
(we have a tool that does this, but I'm not sure we've cleaned it up yet/included it in the distribution - we probably should as I feel like will be a common task :)

What Stella mentions above will make this more efficient as instead of embedding a flatbuffer binary you'd just link in a static library (`clang my_model_main.c -lcompiled_iree_module.a -o my-model`). The executable you build to call your model/load inputs/produce outputs will be the same as seen in simple_embedding_test, though, just have a smaller binary size.

**Comment by marbre** [comment]
As Stella mentioned above, we're working on the integration of [EmitC](https://github.com/iml130/mlir-emitc) into IREE, which will allow to emit IREE's VM as C++ code. We're putting things together and made progress, but e2e isn't possible yet. @simon-camp might want to comment on the status, as he is currently the one primarily working on this.

In addition to Ben's comment, you can also build the `simple_embedding` example out-of-tree as shown in the [iree-template-cpp](https://github.com/iml130/iree-template-cpp) repo.

**Comment by ScottTodd** [comment]
Looks like this question was answered in a few ways, and some of these options have matured quite a bit since the last comments here. Closing the issue for now, but please reach out again if you have other questions.
