### ISSUE TITLE
Python Bindings setup outdated? Can't run e2e keras keyword_spotting_streaming_test.py

### ISSUE THREAD

**Issue by OliverScherf** [iree-org/iree#4905]
I tried to install and use the IREE Python bindings. I build and set up IREE as described in [Get Started Python](https://github.com/google/iree/blob/87d169a59bc6203b8e2813438d9b3a835fbe05da/docs/get_started/getting_started_python.md).

To verify my installation is ran the tests.
All tests are passing when I run the command `ctest -L bindings/python` as well as 

```
python ../iree/integrations/tensorflow/e2e/simple_arithmetic_test.py \
    --target_backends=iree_vmla --artifacts_dir=/tmp/artifacts
```
is passing (skipping `SimpleArithmeticTest.test_session`).

_______

In the Get Started docs there is a section about "Installing and Packaging". However the file `python bindings/python/setup.py` does not exist.
There are some `setup.py` files that are located in:
```
./bindings/python/pyiree/compiler2/setup.py
./bindings/python/pyiree/tools/tf/setup.py
./bindings/python/pyiree/rt/setup.py
```
So I just installed all of them as described.

Now I wanted to run the `cnn` e2e test that is listed in [tensorflow_coverage/language_and_speech_coverage.md](https://github.com/google/iree/blob/87d169a59bc6203b8e2813438d9b3a835fbe05da/docs/tensorflow_coverage/language_and_speech_coverage.md).

~~However running `python ../integrations/tensorflow/e2e/keras/keyword_spotting_streaming_test.py` from the `iree-build` directory will produce the following error:~~

```
Traceback (most recent call last):
  File "../iree/integrations/tensorflow/e2e/keras/keyword_spotting_streaming_test.py", line 25, in <module>
    from kws_streaming.layers import modes
ModuleNotFoundError: No module named 'kws_streaming'
```

EDIT: I cloned the kws_streaming module from the [Google Research Repository](https://github.com/google-research/google-research/tree/master/kws_streaming) and added it to the `PYTHONPATH`. The e2e test is now working.

Maybe this should be documented as well. My issue itself is resolved.

**Comment by stellaraccident** [comment]
Thank you for the report. Yes, there are some doc bugs that need updating. @phoenix-meadowlark would you mind taking a pass through the documented steps from scratch and make sure they are up to date?

Also, I think the kws issue stems from missing a test only dependency. Phoenix: how does the CI resolve this? Should we have a requirements.txt somewhere for test deps and make sure we direct both systems and people to use it?

**Comment by stellaraccident** [comment]
Ok, the issue is that the kws_streaming python package is not installed automatically in our OSS releases. Also, it seems to only be published as part of the google-research repo, which must be checkout out manually.

The following worked for me (assuming that you are checking out to `$HOME/src`):

```shell
cd $HOME/src
git clone https://github.com/google-research/google-research
export PYTHONPATH=$PYTHONPATH:$HOME/src/google-research
```

We should update docs and or have a script to pull/configure such test-only deps.

**Comment by phoenix-meadowlark** [comment]
Ah right, we were linking that in via a bazel http archive so that we wouldn't have to add an IREE-wide dep on google-research, but that disappeared with the rest of the bazel goo. The CI doesn't address this because we're not running the tests. 

It might be possible to add the boiler plate to allow `pip install git+https://github.com/google-research/google-research/kws_streaming` (depends on if git(hub) will let me target a subdir and if I can make python be okay with `setup.py` being inside of `kws_streaming/`). That would make the CI happy and allow people to run the tests as a part of development without managing a `google-research` clone in their pythonpath. I'll investigate.

**Comment by stellaraccident** [comment]
If serious, you may want to talk to Oleg about promoting it to a top-level project, which wouldn't be too hard. Then either submodule or pip install it.

**Comment by stellaraccident** [comment]
For local use, I have gotten this working by:

```
cd ~/src
git clone https://github.com/google-research/google-research.git
```

Then from the CMake build directory:

```
ln -s ~/src/google-research/kws_streaming bindings/python/
```

Also requires an additional package `tensorflow-model-optimization` which I am adding to the integrations/tensorflow/bindings/python/build_requirements.txt`.

We should document and/or script this somewhere.

**Comment by stellaraccident** [comment]
Also seems to have some sensitivity to the precise keras version. We need to triage this more.

**Comment by alliemartens** [comment]
@stellaraccident Another old one, still active?

**Comment by ScottTodd** [comment]
This issue looks stale, closing.
