### ISSUE TITLE
Runtime binaries are larger than expected

### ISSUE THREAD

**Issue by hcindyl** [iree-org/iree#6621]
`iree/samples/simple_embedding` binaries are large.

https://gist.github.com/hcindyl/1c0457d8194abc4fb05fdadfbb79d3a3

In MSVC, where we have a bunch of size-optimized flags enabled, it is 70KB.

Would be nice to find how to reduce the binary size for the baremetal config

**Comment by hcindyl** [comment]
Adding `-DIREE_STATUS_MODE=0 -DIREE_FLAGS_ENABLE_CLI=0 -DIREE_HAL_MODULE_STRING_UTIL_ENABLE=0` reduced the rv32 baremetal size from ~1.99MB to ~1.86MB

**Comment by benvanik** [comment]
Clang on linux for x64 produces a 195KB binary with those options set gzipped to 70KB. That yours is an order of magnitude larger makes me think maybe it's the linker you are using not performing LTO or something?

**Comment by hcindyl** [comment]
It is set to use the default ld. not lld. let me try to play with that too. (btw, should we update the doc to ask users to link with lld for the host build too?)

**Comment by benvanik** [comment]
IMO working with a lot of things but having us only need to maintain the most optimal path for one is a good idea - too many weird compilers/versions out there :) Saying that if one wants to reproduce the smallest/fastest/etc builds we have they use the same compiler/linker we are and otherwise need to understand their toolchain themselves would be good.

**Comment by hcindyl** [comment]
> Clang on linux for x64 produces a 195KB binary with those options set gzipped to 70KB. That yours is an order of magnitude larger makes me think maybe it's the linker you are using not performing LTO or something?

How did you get the 195KB X86_64 output? I add `-DCMAKE_EXE_LINKER_FLAGS="-fusd-ld=lld"` but still get 1.1MB simple_embedding_embedded_sync (no other flags imposed though)

**Comment by benvanik** [comment]
added this to the iree_select_compiler_opts in iree_copts.cmake:
```
    CLANG_OR_GCC
      "-DIREE_STATUS_MODE=0"
      "-DIREE_FLAGS_ENABLE_CLI=0"
      "-DIREE_HAL_MODULE_STRING_UTIL_ENABLE=0"
      "-DIREE_VM_EXT_I64_ENABLE=0"
      "-DIREE_VM_EXT_F32_ENABLE=0"
```

then did
```
rm -rf ../iree-build-wsl-cmake/
cmake -B ../iree-build-wsl-cmake/ -DCMAKE_BUILD_TYPE=MinSizeRel -GNinja .
cmake --build ../iree-build-wsl-cmake/ --target iree_samples_simple_embedding_simple_embedding_embedded_sync
```

nothing else special - just clang 10

**Comment by hcindyl** [comment]
:( The last two flags hits #6620 
I updated
```
diff --git a/build_tools/cmake/iree_copts.cmake b/build_tools/cmake/iree_copts.cmake
index a3a4d420f..87c815852 100644
--- a/build_tools/cmake/iree_copts.cmake
+++ b/build_tools/cmake/iree_copts.cmake
@@ -315,6 +315,17 @@ endif()
 #-------------------------------------------------------------------------------
 
   # TODO(#898): add a dedicated size-constrained configuration.
+iree_select_compiler_opts(IREE_SIZE_OPTIMIZED_DEFAULT_COPTS
+  CLANG_OR_GCC
+    "-DIREE_STATUS_MODE=0"
+    "-DIREE_FLAGS_ENABLE_CLI=0"
+    "-DIREE_HAL_MODULE_STRING_UTIL_ENABLE=0"
+    "-DIREE_VM_EXT_I64_ENABLE=0"
+    "-DIREE_VM_EXT_F32_ENABLE=0"
+)
+set(IREE_DEFAULT_COPTS
+    "${IREE_DEFAULT_COPTS}"
+    "${IREE_SIZE_OPTIMIZED_DEFAULT_COPTS}")
 if(${IREE_SIZE_OPTIMIZED})
   iree_select_compiler_opts(IREE_SIZE_OPTIMIZED_DEFAULT_COPTS
     MSVC_OR_CLANG_CL
```
and run
```
cmake -G Ninja -B out/host/iree_compiler \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_INSTALL_PREFIX=out/host/iree_compiler/install \
    -DIREE_HAL_DRIVERS_TO_BUILD="Dylib;VMVX" \
    -DIREE_TARGET_BACKENDS_TO_BUILD="DYLIB-LLVM-AOT;VMVX" \
    -DIREE_BUILD_TESTS=OFF \
   <iree_src>

cmake --build out/host/iree_compiler/ --target iree/samples/simple_embedding/simple_embedding_embedded_sync
```
My local git repo is synced to e743a1175f40, two commits behind ToT, but I don't think those two commits matter.

**Comment by hcindyl** [comment]
okay, run with 
```
cmake -G Ninja -B out/host/iree_compiler \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_INSTALL_PREFIX=out/host/iree_compiler/install \
    -DIREE_HAL_DRIVERS_TO_BUILD="Dylib;VMVX" \
    -DIREE_TARGET_BACKENDS_TO_BUILD="DYLIB-LLVM-AOT;VMVX" \
    -DIREE_BUILD_TESTS=OFF \
    <iree_src>
cmake --build out/host/iree_compiler/ --target iree/samples/simple_embedding/simple_embedding_embedded_sync
```
results in 220KB

While adding `-DIREE_STATUS_MODE=0 -DIREE_HAL_MODULE_STRING_UTILS_ENABLE=0` as

```
cmake -G Ninja -B out/host/iree_compiler \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_C_FLAGS="-DIREE_STATUS_MODE=0 -DIREE_HAL_MODULE_STRING_UTIL_ENABLE=0" \
    -DCMAKE_INSTALL_PREFIX=out/host/iree_compiler/install \
    -DIREE_HAL_DRIVERS_TO_BUILD="Dylib;VMVX" \
    -DIREE_TARGET_BACKENDS_TO_BUILD="DYLIB-LLVM-AOT;VMVX" \
    -DIREE_BUILD_TESTS=OFF \
    <iree_src>
cmake --build out/host/iree_compiler/ --target iree/samples/simple_embedding/simple_embedding_embedded_sync
```
results in 195KB

Let me try to test on rv32 baremetal config now.

**Comment by hcindyl** [comment]
X86_64 builds simple_embedding_embedded_sync with bare-metal config and -DCMAKE_BUILD_TYPE=MinSizeRel also results in ~220K. RISCV32 Bare-matal with MinSizeRel is still considerably bigger if I don't include the BSP package (i,.e, running `build_tools/cmake/build_riscv.sh` with the CMAKE_BUILD_TYPE change), about 579K.

**Comment by hcindyl** [comment]
I figured out what's wrong with the 1.9MB binary: it is built with debug symbols. :( Without the debug symbols, adding `-DIREE_STATUS_MODE=0 -DIREE_HAL_MODULE_STRING_UTIL_ENABLE=0`, and building with `-DCMAKE_BUILD_TYPE=MinSizeRel, the simple_embedding_embedded_sync for RISC-V 32 bare-metal is 394K, and can be gzipped to 140K.

**Comment by benvanik** [comment]
394K is so big o_O
if you can post a riscv binary with the debug symbols I can fiddle with some size analysis tools

**Comment by benvanik** [comment]
(I don't expect the contents to be much different between archs, but the relative sizes of things may be indicative of some bad code patterns)

**Comment by hcindyl** [comment]
[simple_embedding_embedded_sync.gz](https://github.com/google/iree/files/6928441/simple_embedding_embedded_sync.gz)

Compiled with `-g3 -ggdb -DIREE_STATUS_MODE=0 -DIREE_FLAGS_ENABLE_CLI=0 -DIREE_HAL_MODULE_STRING_UTIL_ENABLE=0` copts and -DCMAKE_BUILD_TYPE=MinSizeRel

**Comment by benvanik** [comment]
Ok cool - looking through with bloaty.
I fixed #6620 as that adds a few KB + some libc/libm stuff you pull in for bare metal. Some of the largest .text regions are also those emulation bits, which is unavoidable when linking everything statically. When trying to measure the size of IREE itself it'd be better to exclude those and not look at the final binary size as it'll be difficult to match between configurations.

You can get bloaty here: https://github.com/google/bloaty
and then I just did
```
./bloaty -d sections,symbols,compileunits,inlines -w -n 0 ../../Dev/iree-build-wsl-cmake/iree/samples/simple_embedding/simple_embedding_embedded_sync > bloaty.txt
```

On RISCV you won't be able to use inlines or compileunits (just `-d sections,symbols`) but if you do an x64 build it'll show you the .c files everything is coming from.

Here's the x64 dump:
https://gist.github.com/benvanik/b280192140738a3669d78ff849abdbc9
and your riscv one:
https://gist.github.com/benvanik/1ec81a4def3494704933bf8dc45e8cc7

It's got some things that stand out that make me think there's some symbol visibility issue in the toolchain or dead code stripping is not enabled. There's a lot of `iree_hal_buffer_view_fprint`-style stuff, which makes me think that though the IREE_HAL_MODULE_STRING_UTIL_ENABLE=0 is specified something else is pulling it in - or it's just not being stripped. I see it on x64 linux too, which is weird. That particular method (`iree_hal_buffer_view_fprint`) is never reachable in simple_embedding_test and shouldn't be there.

Other differences are with i64/f32 disabled the x64 iree_vm_bytecode_dispatch - the largest function - is 10KB vs. the 32KB riscv one. Some of that may also come from the much more verbose unaligned load logic that I would like to remove.

But, for really size-constrained situations, simple_embedding_test is a bad proxy. We should have something using emitc for the VM part and static libraries for the HAL executables. A lot of the code in here (that should be in here) is bytecode and elf stuff. We'll still definitely have some size chopping to do after that (HAL devirtualization, etc) but it's harder to see now.

**Comment by hcindyl** [comment]
Thanks for the investigation! Very insightful share out. We are not that resource constrained so if the execution overhead is at 100K. However, the smaller the merrier, as always.

Are we at a state for which it is possible to provide the emitC VM + HAL executable sample? From`iree/samples/emitc_modules/` it is not obvious to see how the HAL executable part is plugged in (only with the -iree-vm-ir-to-c-module flag)

**Comment by benvanik** [comment]
Ah yes - emitc_modules is the VM side, and then static_library (which we should really rename, as that's so generic it's hard to know what it is) shows how to do the HAL executables - smashing the two together is all that's needed.

Concretely it'd be:
https://github.com/google/iree/blob/3135702b12c8285d9c52eb97158e7305e0a668aa/iree/samples/static_library/static_library_demo.c#L32-L44
for getting the hal executable and
https://github.com/google/iree/blob/58fbb7bdb7940f4974b73af7ec6236482c5df72f/iree/samples/emitc_modules/add_module_test.cc#L24
for getting the vm module

If we enable emitc by default (I think we can now that it's upstream - we'd just remove the IREE_ENABLE_EMITC cmake flag) we should just change the static_library sample to also use emitc - then it really is showing off static linkage of the whole IREE program.

**Comment by simon-camp** [comment]
#7606 adds such an example.

**Comment by benvanik** [comment]
Checking on this using the static_library_demo_c with size optimized flags in MSVC x64:

We're at ~50KB of code and ~10KB of rodata:
![image](https://user-images.githubusercontent.com/75337/176771048-5cbb3858-4684-4ae0-b98b-0008acd083ad.png)
(create_c_module and static_library_demo are the demo files)

Breakdown by object files:
![image](https://user-images.githubusercontent.com/75337/176771703-52ea2958-0485-4165-adaa-2e1787cfc251.png)

These should be smaller on x86/arm as embedded pointer sizes for vtables in rodata and such should be half the size. It'll be in the noise, though, relative to the top-level numbers. There's probably some bytes that can be shaved here and there but we're in the right order of magnitude on things.

Testing with bytecode instead of emitc the bytecode module adds ~18KB + whatever libc/libm stuff is required when f32 is enabled. As noticed above that will be higher in riscv today due to the unaligned load/store emulation in the bytecode handling today (#6580 will eventually reduce that), but is fairly reasonable for a full VM.

The HAL module and the shims it requires are some of the largest parts, including contributes to rodata (hal/exports.inl export name strings). The HAL module also pulls in most of the other stuff like semaphores, devices, string view stuff for pattern matching, etc. Work on #9549 would remove most of this (at least, ~25KB->~5KB). After that the rest is the required types like VM buffers, lists, and modules.

To go smaller than that we'd need zero runtime and pure full-program codegen from the compiler and that's probably a separate project :)

I'm going to call this closed for now - if there's platform-specific work required for binary configuration (proper LTO/symbol stripping/etc) that'd be in a user's cmake configuration instead of ours and the best we'd be able to do is have that in one of the sample project repos. 

I filed #9686 for getting `IREE_SIZE_OPTIMIZED` cmake support for non-MSVC compilers so we can measure our binaries on the CI but that's just for our own tracking and I'm fine with MSVC for now.
