### ISSUE TITLE
Tracy captures produced by benchmark pipeline aren't grouping CPU codegen or GPU zones

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#7219]
<sub>some discussion [on IREE's Discord here](https://discord.com/channels/689900678990135345/760577505840463893/890728906385158225)</sub>

Examples traces can be downloaded from the artifacts tab on https://buildkite.com/iree/iree-benchmark/builds/1107#d697f531-34bf-4372-9942-6d373b8ece5f

Ungrouped CPU zone statistics:
![image](https://user-images.githubusercontent.com/4010439/135497098-cf6f34df-ef4e-465e-8579-315aaef70717.png)

Ungrouped GPU child zone statistics:
![image](https://user-images.githubusercontent.com/4010439/135497264-0bd11330-5573-48d4-88a3-740b2a231043.png)

https://github.com/google/iree/blob/main/build_tools/benchmarks/run_benchmarks_on_android.py is the main script for running those benchmarks and collecting traces from them.

I tried to reproduce this on my Windows development machine with Tracy's capture GUI and CLI and an unrooted Samsung Galaxy S10 and _was_ able to see grouped zones using both the CPU and GPU targets / HAL drivers:
![image](https://user-images.githubusercontent.com/4010439/135497696-e0876e2a-b513-46b8-9c44-500353593b99.png)
![image](https://user-images.githubusercontent.com/4010439/135497755-8136ad80-92d1-41af-a9e9-ca8923126286.png)

**Comment by ScottTodd** [comment]
things left to check to get a repro:

- [ ] the capture tool built + used for the pipeline on Linux
- [ ] the lab phones
- [ ] the python scripts used for the pipeline

**Comment by antiagainst** [comment]
I tried running the `run_benchmarks_on_android.py` script to benchmark on a local Android phone from a x86 Linux host. Everything works fine. Then I tried to on an aarch64 host (Raspberry Pi 4), it is not working.  It's the same script, the same artifacts (benchmark suites, `iree-benchmark-module`), and the same phone. What's different is the Tracy `capture` tool. I have a tracy `capture` tool compiled for aarch64 for the latter case. In the lab we also use RPI4 to drive the phones. 

So right now I suspect there are issues with Tracy `capture` tool compiled towards aarch64. Or maybe it's due to that we capture with a `capture` tool compiled for aarch64 and view the capture with a Tracy GUI tool compiled for x86? That's problematic? 

I also tried Ben's https://github.com/wolfpld/tracy/pull/262. That does not help either.

**Comment by antiagainst** [comment]
@benvanik: I don't know much internals about Tracy. So the above is more of my guess. Does it make sense?

**Comment by antiagainst** [comment]
> So right now I suspect there are issues with Tracy capture tool compiled towards aarch64. Or maybe it's due to that we capture with a capture tool compiled for aarch64 and view the capture with a Tracy GUI tool compiled for x86? That's problematic?

With my Apple M1 macbook, I have both the `capture` tool and the profiler UI compiled for aarch64 and it works fine. But still I cannot use the profiler UI to open the captures generated from those RPI devices (which is also aarch64).. So I guess it might have something to do with the libraries Tracy depends on Ubuntu?

**Comment by benvanik** [comment]
I still have issues loading those android traces - I think I tracked it down to something that looked like undefined behavior somewhere in either the recording of string tables or the parsing of them but wasn't able to figure it out.

**Comment by antiagainst** [comment]
Yeah, me too. This bug is really wild.. Time to update Tracy though! It has been almost a quarter. :)

**Comment by ScottTodd** [comment]
I wonder if this reproduces on the latest Tracy / newer phones. This issue is quite old 🤔

**Comment by ScottTodd** [comment]
We switched from builtkite to github actions and then later dropped Tracy support from the benchmarks pipelines. Closing this old issue.
