### ISSUE TITLE
Problem when using iree-run-trace

### ISSUE THREAD

**Issue by chiachia36** [iree-org/iree#7540]
Hi,
I want to use `iree-run-trace` to check dump traces on RISC-V QEMU.

I set the directory for dumping traces and run the file [mobilenet_v2_test.py](https://github.com/google/iree-samples/blob/main/tflitehub/mobilenet_v2_test.py).
I got `calls.yaml` and `module.vmfb`.
Then, I tried to run the .yaml file.
Here is my command.
```
${QEMU_BIN} \
  -cpu rv64,x-v=true,x-k=true,vlen=256,elen=64,vext_spec=v1.0 \
  -L ${RISCV_TOOLCHAIN_ROOT}/sysroot/ \
  ../iree-build-riscv/iree/tools/iree-run-trace --driver=dylib \
  ${HOME}/ic8/iree_trace/mobilenet_v2/calls.yaml
```
I get some error message.
```
--- CALL[module.main] ---
<vm>:0: UNKNOWN; device not supported in the compiled configuration;
[ 0] bytecode module.main:2028 "module/hub_input/images_uint8_dequantized"
      at "main"; replaying trace file '/users/student/mr108/cwlu19/ic8/iree_trace/mobilenet_v2/calls.yaml'
```
Did I misunderstand the usage of `iree-run-trace` or anything else?
Thanks!

**Comment by GMNGeoffrey** [comment]
Pretty sure your VMFB is going to be compiled for the wrong target. I'm honestly not sure how the samples tests work, but if you're executing the test on your computer, it's almost certainly being compiled for your host architecture.

@rsuderman can you help here? Is there a way to get the samples tests to spit out vmfb for other architectures?

**Comment by rsuderman** [comment]
I have little to no experience with iree-run-trace. @GMNGeoffrey who is the resident expert on the tracing work?

**Comment by benvanik** [comment]
I think it was routed to you because the issue is that the sample python stuff needs to be configured with the right target flags for riscv but we aren't sure how to do that. However it's invoked today is just picking the host configuration (x86-64 etc) and that naturally won't run on riscv :)
Do you have any examples of setting the flags when exporting the vmfbs? (I literally haven't ever looked - it may just be in the docs)

**Comment by GMNGeoffrey** [comment]
Yeah this issue actually has nothing to do with the trace work. It makes sense that the sample is outputting a vmfb for x86-64 because it's actually running that vmfb on that host. The place where I'd expect it to output one for RISC-V would be if the test were run on RISC-V, but I'm not sure they even work there (the python part of it).

For accomplishing what  you're actually trying to accomplish @chiachia36, I would recommend just using that same TFLite flatbuffer that the test is using and compiling it via `iree-import-tflite` followed by `iree-translate`. It would be nice if this were hooked into the tests in an easily-usable way, but this would be part of a general infra effort to allow python tests to generate artifacts to run on arbitrary architectures, which has been postponed for now.

LMK if you need help figuring out how to use those tools. https://google.github.io/iree/ml-frameworks/tensorflow-lite/ is the relevant documentation. I don't know the exact flags you need to run on RISC-V. @hcindyl would probably be able to help you with that

**Comment by hcindyl** [comment]
iree-samples currently is not set to test non-x86_64 target. You need to pass more `iree-translate` flags in https://github.com/google/iree-samples/blob/main/tflitehub/test_util.py#L120. An example of how to build/test rv64 target via CLI is at https://github.com/google/iree/blob/main/build_tools/kokoro/gcp_ubuntu/cmake/linux/riscv64/test.sh#L38-L53
