### ISSUE TITLE
IR not optimized for efficient GPU use

### ISSUE THREAD

**Issue by nirvedhmeshram** [iree-org/iree#8315]
Hello, 
I have the following linalg IR
https://gist.github.com/nirvedhmeshram/aeead91519916115aa5424cffd788cdd
I want to run on the GPU and I use the following translate command
```
~/iree-build-release/iree/tools/iree-translate -iree-mlir-to-vm-bytecode-module -iree-hal-target-backends=cuda  ~/hbc_verification/hbc_new.mlir -o ~/testhbc_gpuallarguments.vmfb --iree-cuda-llvm-target-arch=sm_80 --iree-hal-cuda-disable-loop-nounroll-wa --iree-enable-fusion-with-reduction-op
```
I notice as it lowers we have two dispatch.workgroups. See this IR made earlier on.
 https://gist.github.com/nirvedhmeshram/508394fa46d003fe15446cd7af8a40d6
The result is I get two kernels (2 us each) and a 240 us gap between them, hence defeating the purpose of doing this on the GPU. How could something like this be made more efficient. Please let me know and I can provide you with a full dump.

**Comment by benvanik** [comment]
At the mid- to low-level of the stack that IREE operates at the rule as to what runs on the host vs. device is very simple: ops operating on tensors run on device and everything else runs on the host.

With that in mind, there are two two major issues arising from whatever frontend produced this input that pessimizes performance: it uses assertions for control flow and it computes shapes using tensors. The assertions block code motion, dispatch region fusion, and stream fusion and introduce additional host/device synchronization. The shape computations that require upload, dispatch, and download of the resulting shapes also introduce host/device synchronization. The combination of these two is particularly painful as we may be able to hoist/fold/etc some of the shape computations but the assertions act as barriers that prevent that.

You can pass `-iree-opt-strip-assertions` to at least get rid of the assertions. That will at least allow more code motion and folding. In general you'll never want to look at performance with assertions enabled, just like you wouldn't try to profile debug builds of a C app with NDEBUG not defined and assertions left in. There's upstream work that could make the assertions less bad (there's nothing that folds redundant assertions today, for example), but they'll never be good.

Detensoring as in #1159 is required to turn the shape-computations-using-tensors into the primitive math they should be. It'll always be better for frontends to emit shape calculations as normal math instead of tensors but the detensoring should be able to help in situations like this. You may be able to use the `-iree-flow-enable-linalg-detensorize` flag to try it out - it could have bitrotted as it was never finished. @ScottTodd this may be the input you were looking for to test things.

If you're expecting to be passing in input programs that do both of these things there'll need to be work done on both these paths to make them better supported.

**Comment by benvanik** [comment]
(if you pass `-iree-scheduling-dump-statistics-format=pretty` it would probably print out that there are 2+ d->h syncs and 2+ submissions - that's an easy way to spot these kind of issues - today most programs end up as 1 of each, and in the future the goal is 0)

**Comment by nirvedhmeshram** [comment]
Thanks Ben, makes sense. The `-iree-opt-strip-assertions` made a difference
Before
```
//   Constants: 0, 0 B (0.00 MiB)
//   Variables: 0, 0 B (0.00 MiB)
//  D->H Syncs: 2
// Submissions: 2, using cumulative minimum 0 B (0.00 MiB)
//   DMA Fills: 2
//  DMA Copies: 0
//  Dispatches: 2
// Executables: 2, 0% reuse
```
After (changed fields)
```
//  D->H Syncs: 1
// Submissions: 1, using cumulative minimum 0 B (0.00 MiB)
```
However in both cases we still have 2 dispatches and while the perf improved, its still not very good. And yes `-iree-flow-enable-linalg-detensorize` did not make any difference. 

@cathyzhyi Do you think it will be easy in torch-mlir to have a front end that can `emit shape calculations as normal math instead of tensors`
@benvanik Would you expect shapes as normal math to solve the 2 dispatch problem?

**Comment by stellaraccident** [comment]
@silvasean 

I believe it should be possible to both scalarize the shape math and hoist assertions. There are a bummer of pieces for this, but this is some of the first time they've come together.

(These are some of the first programs from this frontend so not terribly surprising things are not lining up precisely in one shot)
