### ISSUE TITLE
calling external library functions from Linalg-on-tensors operations

### ISSUE THREAD

**Issue by JasonMaojinsong** [iree-org/iree#9142]
Hi  

is there any plan in IREE  to support calling externel library functions from Linalg-on-tensors operations,  as linalg dialect has this property, and we want to implement the reference function for hardware target simulation or calling the hardware API directly.  
not sure if this is the best method,  better suggestion are also welcome,  thanks in advance. 

jinsong

**Comment by stellaraccident** [comment]
Thank you for the request. There are quite a few ways to do such things. Could you comment more on the specifics you are looking for? Examples of things that would be useful:

* Which linalg op(s) most interest you?
* Presumably this is for CPU targets?
* How are you using the runtime, and is there a preferred way to locate the backing library implementation? (i.e. are you building your own IREE runtime and looking to static link, is dynamic linking workable, or is this a C/bare-metal implementation that has everything linked into one binary)
* Any opinion on how this is exposed (i.e. compiler options/config file to map ops to calls)?

There are various ways to hack this today for a one-off, but we'd ultimately like to produce something relatively reusable.

**Comment by JasonMaojinsong** [comment]
Hi Stella,

The reason why don't use lowering to llvm is that specific backend (NPU) simulation in fixed point implementation for our hardware,  looks it's similar to call the GPU kernel in some way, maybe Linalg is not the proper Dialect level, we wish to hear your suggestions.  please correct me if I am wrong. 

regarding the details:
1,  conv2d, matmul, sigmoid, tanh, relu most intrest us.
2,  this is for NPU targets,  which implemented the int8 fixed point data point,  we want to simulate the backend behavior.
3,  the current IREE runtime looks good to us, static/dynamic link/bare-metal are all okay, debug into the kernel is needed fix bug in kernel implementation.
4,  it's better to exposed with options,  like "-naive " is to simulate on cpu kernel(function correct),  "--backend" is to run really on hardware (performance). 

many thanks

**Comment by JasonMaojinsong** [comment]
@stellaraccident 
Hi Stella,

The reason why don't use lowering to llvm is that specific backend (NPU) simulation in fixed point implementation for our hardware, looks it's similar to call the GPU kernel in some way, maybe Linalg is not the proper Dialect level, we wish to hear your suggestions. please correct me if I am wrong.

regarding the details:
1, conv2d, matmul, sigmoid, tanh, relu most intrest us.
2, this is for NPU targets, which implemented the int8 fixed point data point, we want to simulate the backend behavior.
3, the current IREE runtime looks good to us, static/dynamic link/bare-metal are all okay, debug into the kernel is needed fix bug in kernel implementation.
4, it's better to exposed with options, like "-naive " is to simulate on cpu kernel(function correct), "--backend" is to run really on hardware (performance).

many thanks

**Comment by stellaraccident** [comment]
Yeah, in general the "hardware wins" scenario is where this is the most advantageous. As Ben mentioned on discord, there are multiple ways to do this, and we are interested in supporting some of the scenarios but are being cautious in order to ground it out on real use cases where there is a hardware benefit (vs just a software layering issue).

There will be multiple issues here:

1. Even an input dialect like TOSA/MHLO is typically more decomposed than your question suggests you want. Typically, conv2d and matmul remain ops in this world, but sigmoid/tanh/relu are not necessarily a 1:1 match. In my experience, most hardware accelerates some configurations of things like conv2d/matmul, but the others just happen to have good library implementations. It is useful to distinguish, because in the long run, you want the compiler targeting the hardware, not just some generation of software layered on top of it.
2. It sounds like you have both on-hardware and simulation requirements. For simulation, there may be lighter weight options than would be available for a full accelerated hardware implementation.
3. Different lowerings can be implemented for the CPU backend which then call out to library functions, but you may actually be looking for a backend just for your supported hardware -- and then let IREE run in "multiple device" mode so that it can codegen most things and dispatch to the custom backend for fixed-function units.

I'm not going to lie to you -- we are interested in supporting various aligned NPU workflows, but the path from where we are to there is going to be steep on the compiler side. If the runtime is roughly what you want, then it is possible to build a dedicated compiler which uses the high level components of IREE's compiler but delegates to more fixed function backends only. We don't have an example of such a thing, but we have sketched it a few times. This isn't going to be a "here's the simple answer" kind of situation and it will require co-investment. We can likely sketch out a direction that would work, but actually getting our help to implement it is going to be dependent on timing/prioritization/importance to us. It would be a commitment (from both sides) to get the best outcome.

**Comment by benvanik** [comment]
We now have end-to-end support for calling custom microkernel imports from CPU codegen in #10865 and/or custom CPU executable loaders can be plugged in to support arbitrary dispatch representations produced by custom compiler HAL targets. This should allow users to extend things in whatever direction they want without needing to land specialized code in the main IREE repo.
