### ISSUE TITLE
Segfault when creating multiple IREE SystemContexts

### ISSUE THREAD

**Issue by hawkinsp** [iree-org/iree#9277]
Repro with `iree_runtime==20220601.156`:

```
In [1]: import iree.runtime

In [2]: ctx = iree.runtime.SystemContext(config=iree.runtime.Config("dylib"))

In [3]: ctx2 = iree.runtime.SystemContext(config=iree.runtime.Config("dylib"))
zsh: segmentation fault
```

I'd expect a graceful failure not a segfault.

**Comment by stellaraccident** [comment]
Indeed.. The actual issue is two configs, not two contexts. If you have one global config, that will work.

(The config API has been in need of work for a long time. Historically we've held off on doing to much there until we have better low level APIs for default config/multi device -- but even barring that, as you say, a crash is not ok and should be fixed)

**Comment by hawkinsp** [comment]
Note that it's easy to do this in ways that are more subtle. e.g., I think calling `load_vm_flatbuffer` twice in the same program has the same issue, because it creates a `Config` internally. That's an API footgun...

**Comment by stellaraccident** [comment]
Let me take a pass through and clean this up (probably tomorrow). This part of the API has existed since day 1 as a poc and had never gotten any real attention.

**Comment by rsuderman** [comment]
Tested at head and no longer failing.
