### ISSUE TITLE
IREE hardfaults on Arm bare-metal target when dispatching a 64bit op

### ISSUE THREAD

**Issue by marbre** [iree-org/iree#9593]
### What happened?

After bumping the IREE submodule in the [iree-bare-metal-arm](https://github.com/iml130/iree-bare-metal-arm) from candidate-20220518.142 to candidate-20220519.143, a hardfault occurs on Arm bare-metal targets. This issue is related to the changes introduced with #9145 or at least this change reveals the issue. The issue was verified on several STM32 (Cortex-M4 / Armv7-M) targets and also occurs with Arm's FVP (Fixed Virtual Platform) for the Corstone-300 (Cortex-M55 / Armv8.1-M).

### Steps to reproduce your issue

See https://gist.github.com/marbre/f26c1fc96c3dd4796ff2f31ec42f46b9

### What component(s) does this issue relate to?

Runtime

### Version information

Commit google/iree@395d248 and [candidate-20220519.143](https://github.com/google/iree/releases/tag/candidate-20220519.143), respectively. 

### Additional context

Debugging on an Nulceo-64 with STM32F411RE, I could trace down the error to occur when dispatching a `ConstI64` op:
https://github.com/google/iree/blob/395d248e8bb9c7c221ec2e0dd18b833074e1f336/runtime/src/iree/vm/bytecode_dispatch.c#L872

The issue can be bypassed by adding `-mno-unaligned-access` to our toolchain file. With this, the preprocessor symbol `__ARM_FEATURE_UNALIGNED` isn't defined and `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED`is set accordingly:

https://github.com/google/iree/blob/395d248e8bb9c7c221ec2e0dd18b833074e1f336/runtime/src/iree/base/target_platform.h#L149-L156

(Please note that just passing `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` via CMake's `add_compile_definitions` wasn't sufficient.)
With `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` set, the functions for aligned memory access are defined in [alignment.h](https://github.com/google/iree/blob/candidate-20220519.143/runtime/src/iree/base/alignment.h). Else the following code is compiled:

https://github.com/google/iree/blob/395d248e8bb9c7c221ec2e0dd18b833074e1f336/runtime/src/iree/base/alignment.h#L185-L197

This implements loads and stores for all data types. However, according to the [Cortex-M4 Technical Reference Manual](https://developer.arm.com/documentation/ddi0439/b/Programmers-Model/System-address-map/Unaligned-accesses-that-cross-regions?lang=en) unaligned access isn't available for all bit widths:

> Unaligned support is only available for load/store singles (LDR, STR). Load/store double already supports word aligned accesses, but does not permit other unaligned accesses, and generates a fault if this is attempted.

I am not sure if we should enforce `-mno-unaligned-access` to be set or if we should rather refactor [alignment.h](https://github.com/google/iree/blob/candidate-20220519.143/runtime/src/iree/base/alignment.h) in a way to only use unalignment memory access where supported.
I further have to mention that there might be more that goes wrong, since just defining `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` didn't resolved the issue.

For the sake of completeness, `-mno-unaligned-access` is documented in [GCC's docs](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html) as follows:

> Enables (or disables) reading and writing of 16- and 32- bit values from addresses that are not 16- or 32- bit aligned. By default unaligned access is disabled for all pre-ARMv6, all ARMv6-M and for ARMv8-M Baseline architectures, and enabled for all other architectures. If unaligned access is not enabled then words in packed data structures are accessed a byte at a time.

> The ARM attribute Tag_CPU_unaligned_access is set in the generated object file to either true or false, depending upon the setting of this option. If unaligned access is enabled then the preprocessor symbol __ARM_FEATURE_UNALIGNED is also defined.

**Comment by benvanik** [comment]
Fantastic investigation! I agree with you that since the changes didn't touch the definition of ConstI64Op or its generation in the compiler I suspect this was a latent issue exposed because with #9145 most programs will have at least some i64 values in them for buffer offsets and such.

I still would like to make the bytecode follow natural alignment rules so that we can get rid of all of the unaligned handling as part of #6580, but in the meantime we should probably work around this. The complicated part is that we would be wasting a tremendous amount of space to perform the alignment (5-7 out of every 16 bytes would be wasted padding), but #3964 may help mitigate that as we'd only need to align the table once and then all constants contained would be guaranteed aligned.

Given the ARM docs it sounds like at a minimum we'd need to add special handling of 64-bit types (I imagine other 32-bit archs may have similar restrictions), so it's probably worth splitting that alignment required flag into `_16`, `_32`, and `_64` (or whatever) versions and setting that in `target_platform.h` to control the `alignment.h` behavior.

You mention that there are still issues once this is fixed - it'd probably be good to land the improvements that make us at least attempt to avoid the unaligned accesses and then do another round of investigation to find where we're not properly using the helper macros. My fear is that some may be in generated code, but that may just mean some additional llvm flags passed to iree-compile (we can loop in codegen folks for that if it turns out to be the case).

**Comment by marbre** [comment]
> Given the ARM docs it sounds like at a minimum we'd need to add special handling of 64-bit types (I imagine other 32-bit archs may have similar restrictions), so it's probably worth splitting that alignment required flag into _16, _32, and _64 (or whatever) versions and setting that in target_platform.h to control the alignment.h behavior.

From what I've read so far, it's mainly unaligned 64-bit data. However, there are also some instructions on Armv8-M like `LDAH` (loads a halfword from memory, zero-extends it to form a 32-bit word and writes it to a register) for which non-half word memory access generates an alignment fault. Anyway, starting with IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED_**64** should be fine and is at least sufficient for Armv7-M. So it seems it is not strictly necessary to further split into _8_16 and _32. WDYT?

> You mention that there are still issues once this is fixed - it'd probably be good to land the improvements that make us at least attempt to avoid the unaligned accesses and then do another round of investigation to find where we're not properly using the helper macros. My fear is that some may be in generated code, but that may just mean some additional llvm flags passed to iree-compile (we can loop in codegen folks for that if it turns out to be the case).

That should be fixed with #9697. I assume one should be able to control the alignment behavior with `IREE_MEMORY_ACCESS_ALIGNMENT_REQUIRED` from the outside. Right now you need `-mno-unaligned-access` for this.
