### ISSUE TITLE
error creating device vulkan : how to set device id ?

### ISSUE THREAD

**Issue by flo-th** [iree-org/iree#9888]
Hi all,

After the compilation of a model for android vulkan device, the following error is raised when i try to run it with a runtime compiled with the flag -DIREE_HAL_DRIVER_VULKAN=ON :
`UNIMPLEMENTED; VK_ERROR_FEATURE_NOT_PRESENT; creating device 'vulkan'`
Should i consider an error during the compilation of my runtime (missing HAL library ? -> not compiled by default ?)
How could i check that default vulkan device id called on my android target is the right one ?

Thanks.

**Comment by benvanik** [comment]
As @antiagainst mentioned in Discord this is because your device is missing a required feature ("FEATURE_NOT_PRESENT") - he has some tips for checking what your device supports:
https://discord.com/channels/689900678990135345/689959648501039106/1001149477643628645

The only major thing we require is timeline semaphores - ensure your device/driver supports those (e.g. https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_timeline_semaphore&platform=android).
